
//#line 18 "/Users/nystrom/work/x10/cvs/p3/x10.compiler/src/x10/parser/x10.g"
//
// Licensed Material
// (C) Copyright IBM Corp, 2006
//

package x10.parser;

public interface X10Parsersym {
    public final static int
      TK_IntegerLiteral = 77,
      TK_LongLiteral = 78,
      TK_FloatingPointLiteral = 79,
      TK_DoubleLiteral = 80,
      TK_CharacterLiteral = 81,
      TK_StringLiteral = 82,
      TK_MINUS_MINUS = 83,
      TK_OR = 114,
      TK_MINUS = 89,
      TK_MINUS_EQUAL = 115,
      TK_NOT = 91,
      TK_NOT_EQUAL = 116,
      TK_REMAINDER = 108,
      TK_REMAINDER_EQUAL = 117,
      TK_AND = 118,
      TK_AND_AND = 131,
      TK_AND_EQUAL = 119,
      TK_LPAREN = 5,
      TK_RPAREN = 75,
      TK_MULTIPLY = 107,
      TK_MULTIPLY_EQUAL = 120,
      TK_COMMA = 87,
      TK_DOT = 92,
      TK_DIVIDE = 109,
      TK_DIVIDE_EQUAL = 121,
      TK_COLON = 96,
      TK_SEMICOLON = 76,
      TK_QUESTION = 133,
      TK_AT = 1,
      TK_LBRACKET = 74,
      TK_RBRACKET = 100,
      TK_XOR = 122,
      TK_XOR_EQUAL = 123,
      TK_LBRACE = 88,
      TK_OR_OR = 134,
      TK_OR_EQUAL = 124,
      TK_RBRACE = 97,
      TK_TWIDDLE = 93,
      TK_PLUS = 90,
      TK_PLUS_PLUS = 84,
      TK_PLUS_EQUAL = 125,
      TK_LESS = 110,
      TK_LEFT_SHIFT = 101,
      TK_LEFT_SHIFT_EQUAL = 126,
      TK_RIGHT_SHIFT = 102,
      TK_RIGHT_SHIFT_EQUAL = 127,
      TK_UNSIGNED_RIGHT_SHIFT = 103,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 128,
      TK_LESS_EQUAL = 111,
      TK_EQUAL = 95,
      TK_EQUAL_EQUAL = 129,
      TK_GREATER = 112,
      TK_GREATER_EQUAL = 113,
      TK_ELLIPSIS = 139,
      TK_RANGE = 135,
      TK_ARROW = 85,
      TK_DARROW = 132,
      TK_SUBTYPE = 104,
      TK_SUPERTYPE = 105,
      TK_abstract = 7,
      TK_as = 39,
      TK_assert = 46,
      TK_async = 47,
      TK_ateach = 48,
      TK_atomic = 21,
      TK_await = 49,
      TK_break = 50,
      TK_case = 29,
      TK_catch = 32,
      TK_class = 12,
      TK_clocked = 33,
      TK_const = 20,
      TK_continue = 51,
      TK_def = 15,
      TK_default = 30,
      TK_do = 52,
      TK_else = 40,
      TK_extends = 34,
      TK_extern = 22,
      TK_false = 53,
      TK_final = 8,
      TK_finally = 35,
      TK_finish = 54,
      TK_for = 55,
      TK_foreach = 56,
      TK_future = 94,
      TK_in = 106,
      TK_to = 136,
      TK_goto = 57,
      TK_has = 58,
      TK_here = 59,
      TK_if = 60,
      TK_implements = 41,
      TK_import = 36,
      TK_incomplete = 23,
      TK_instanceof = 31,
      TK_interface = 10,
      TK_local = 24,
      TK_native = 25,
      TK_new = 61,
      TK_next = 62,
      TK_nonblocking = 26,
      TK_now = 63,
      TK_null = 64,
      TK_or = 42,
      TK_package = 37,
      TK_private = 2,
      TK_property = 27,
      TK_protected = 3,
      TK_public = 4,
      TK_return = 65,
      TK_safe = 11,
      TK_self = 66,
      TK_sequential = 28,
      TK_static = 6,
      TK_strictfp = 9,
      TK_super = 43,
      TK_switch = 67,
      TK_synchronized = 140,
      TK_this = 38,
      TK_throw = 68,
      TK_throws = 44,
      TK_transient = 16,
      TK_true = 69,
      TK_try = 70,
      TK_type = 14,
      TK_unsafe = 71,
      TK_val = 17,
      TK_value = 13,
      TK_var = 18,
      TK_volatile = 19,
      TK_when = 72,
      TK_while = 45,
      TK_EOF_TOKEN = 130,
      TK_IDENTIFIER = 73,
      TK_SlComment = 141,
      TK_MlComment = 142,
      TK_DocComment = 143,
      TK_ErrorId = 98,
      TK_any = 137,
      TK_current = 138,
      TK_SynchronizedStatement = 99,
      TK_ObjectKind = 144,
      TK_ArrayInitailizer = 86,
      TK_ERROR_TOKEN = 145;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "AT",
                 "private",
                 "protected",
                 "public",
                 "LPAREN",
                 "static",
                 "abstract",
                 "final",
                 "strictfp",
                 "interface",
                 "safe",
                 "class",
                 "value",
                 "type",
                 "def",
                 "transient",
                 "val",
                 "var",
                 "volatile",
                 "const",
                 "atomic",
                 "extern",
                 "incomplete",
                 "local",
                 "native",
                 "nonblocking",
                 "property",
                 "sequential",
                 "case",
                 "default",
                 "instanceof",
                 "catch",
                 "clocked",
                 "extends",
                 "finally",
                 "import",
                 "package",
                 "this",
                 "as",
                 "else",
                 "implements",
                 "or",
                 "super",
                 "throws",
                 "while",
                 "assert",
                 "async",
                 "ateach",
                 "await",
                 "break",
                 "continue",
                 "do",
                 "false",
                 "finish",
                 "for",
                 "foreach",
                 "goto",
                 "has",
                 "here",
                 "if",
                 "new",
                 "next",
                 "now",
                 "null",
                 "return",
                 "self",
                 "switch",
                 "throw",
                 "true",
                 "try",
                 "unsafe",
                 "when",
                 "IDENTIFIER",
                 "LBRACKET",
                 "RPAREN",
                 "SEMICOLON",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "ARROW",
                 "ArrayInitailizer",
                 "COMMA",
                 "LBRACE",
                 "MINUS",
                 "PLUS",
                 "NOT",
                 "DOT",
                 "TWIDDLE",
                 "future",
                 "EQUAL",
                 "COLON",
                 "RBRACE",
                 "ErrorId",
                 "SynchronizedStatement",
                 "RBRACKET",
                 "LEFT_SHIFT",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "SUBTYPE",
                 "SUPERTYPE",
                 "in",
                 "MULTIPLY",
                 "REMAINDER",
                 "DIVIDE",
                 "LESS",
                 "LESS_EQUAL",
                 "GREATER",
                 "GREATER_EQUAL",
                 "OR",
                 "MINUS_EQUAL",
                 "NOT_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "EQUAL_EQUAL",
                 "EOF_TOKEN",
                 "AND_AND",
                 "DARROW",
                 "QUESTION",
                 "OR_OR",
                 "RANGE",
                 "to",
                 "any",
                 "current",
                 "ELLIPSIS",
                 "synchronized",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "ObjectKind",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
