EXECS = span 

SIMPLE_DIR = ../simple-4.4G

OPT         = -O$(O_LEVEL)
# OPT       = -g

include ./Makefile.smp.mk

# DO NOT DELETE

obj/r_graph.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
obj/r_graph.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
obj/r_graph.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
obj/r_graph.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/r_graph.o: /usr/include/iso/stdio_c99.h /usr/include/stdlib.h
obj/r_graph.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
obj/r_graph.o: graph.h
obj/span.o: /usr/include/sys/types.h /usr/include/sys/feature_tests.h
obj/span.o: /usr/include/sys/ccompile.h /usr/include/sys/isa_defs.h
obj/span.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/span.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
obj/span.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/span.o: ../simple-4.4G/include/simple.h /usr/include/pthread.h
obj/span.o: /usr/include/sched.h ../simple-4.4G/include/mach_def.h
obj/span.o: ../simple-4.4G/include/smp_node.h /usr/include/stdio.h
obj/span.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
obj/span.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/span.o: /usr/include/iso/stdio_c99.h /usr/include/stdlib.h
obj/span.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
obj/span.o: ../simple-4.4G/include/types.h /usr/include/ctype.h
obj/span.o: /usr/include/iso/ctype_iso.h /usr/include/iso/ctype_c99.h
obj/span.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/span.o: /usr/include/sys/resource.h /usr/include/math.h
obj/span.o: /usr/include/iso/math_iso.h /usr/include/iso/math_c99.h
obj/span.o: /usr/include/string.h /usr/include/iso/string_iso.h
obj/span.o: ../simple-4.4G/include/timing.h graph.h
obj/span_bfs_localq.o: ../simple-4.4G/include/simple.h /usr/include/pthread.h
obj/span_bfs_localq.o: /usr/include/sys/feature_tests.h
obj/span_bfs_localq.o: /usr/include/sys/ccompile.h
obj/span_bfs_localq.o: /usr/include/sys/isa_defs.h /usr/include/sys/types.h
obj/span_bfs_localq.o: /usr/include/sys/machtypes.h
obj/span_bfs_localq.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/span_bfs_localq.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
obj/span_bfs_localq.o: /usr/include/sys/time.h /usr/include/sched.h
obj/span_bfs_localq.o: ../simple-4.4G/include/mach_def.h
obj/span_bfs_localq.o: ../simple-4.4G/include/smp_node.h /usr/include/stdio.h
obj/span_bfs_localq.o: /usr/include/iso/stdio_iso.h
obj/span_bfs_localq.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/span_bfs_localq.o: /usr/include/stdio_impl.h /usr/include/iso/stdio_c99.h
obj/span_bfs_localq.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/span_bfs_localq.o: /usr/include/iso/stdlib_c99.h
obj/span_bfs_localq.o: ../simple-4.4G/include/types.h /usr/include/ctype.h
obj/span_bfs_localq.o: /usr/include/iso/ctype_iso.h
obj/span_bfs_localq.o: /usr/include/iso/ctype_c99.h /usr/include/errno.h
obj/span_bfs_localq.o: /usr/include/sys/errno.h /usr/include/sys/resource.h
obj/span_bfs_localq.o: /usr/include/math.h /usr/include/iso/math_iso.h
obj/span_bfs_localq.o: /usr/include/iso/math_c99.h /usr/include/string.h
obj/span_bfs_localq.o: /usr/include/iso/string_iso.h
obj/span_bfs_localq.o: ../simple-4.4G/include/timing.h graph.h
obj/span_breadth_B2.o: ../simple-4.4G/include/simple.h /usr/include/pthread.h
obj/span_breadth_B2.o: /usr/include/sys/feature_tests.h
obj/span_breadth_B2.o: /usr/include/sys/ccompile.h
obj/span_breadth_B2.o: /usr/include/sys/isa_defs.h /usr/include/sys/types.h
obj/span_breadth_B2.o: /usr/include/sys/machtypes.h
obj/span_breadth_B2.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/span_breadth_B2.o: /usr/include/sys/time_impl.h /usr/include/sys/time.h
obj/span_breadth_B2.o: /usr/include/sys/time.h /usr/include/sched.h
obj/span_breadth_B2.o: ../simple-4.4G/include/mach_def.h
obj/span_breadth_B2.o: ../simple-4.4G/include/smp_node.h /usr/include/stdio.h
obj/span_breadth_B2.o: /usr/include/iso/stdio_iso.h
obj/span_breadth_B2.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/span_breadth_B2.o: /usr/include/stdio_impl.h /usr/include/iso/stdio_c99.h
obj/span_breadth_B2.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/span_breadth_B2.o: /usr/include/iso/stdlib_c99.h
obj/span_breadth_B2.o: ../simple-4.4G/include/types.h /usr/include/ctype.h
obj/span_breadth_B2.o: /usr/include/iso/ctype_iso.h
obj/span_breadth_B2.o: /usr/include/iso/ctype_c99.h /usr/include/errno.h
obj/span_breadth_B2.o: /usr/include/sys/errno.h /usr/include/sys/resource.h
obj/span_breadth_B2.o: /usr/include/math.h /usr/include/iso/math_iso.h
obj/span_breadth_B2.o: /usr/include/iso/math_c99.h /usr/include/string.h
obj/span_breadth_B2.o: /usr/include/iso/string_iso.h
obj/span_breadth_B2.o: ../simple-4.4G/include/timing.h graph.h stack.h
obj/verify.o: ../simple-4.4G/include/simple.h /usr/include/pthread.h
obj/verify.o: /usr/include/sys/feature_tests.h /usr/include/sys/ccompile.h
obj/verify.o: /usr/include/sys/isa_defs.h /usr/include/sys/types.h
obj/verify.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/verify.o: /usr/include/sys/select.h /usr/include/sys/time_impl.h
obj/verify.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/verify.o: /usr/include/sched.h ../simple-4.4G/include/mach_def.h
obj/verify.o: ../simple-4.4G/include/smp_node.h /usr/include/stdio.h
obj/verify.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
obj/verify.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/verify.o: /usr/include/iso/stdio_c99.h /usr/include/stdlib.h
obj/verify.o: /usr/include/iso/stdlib_iso.h /usr/include/iso/stdlib_c99.h
obj/verify.o: ../simple-4.4G/include/types.h /usr/include/ctype.h
obj/verify.o: /usr/include/iso/ctype_iso.h /usr/include/iso/ctype_c99.h
obj/verify.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/verify.o: /usr/include/sys/resource.h /usr/include/math.h
obj/verify.o: /usr/include/iso/math_iso.h /usr/include/iso/math_c99.h
obj/verify.o: /usr/include/string.h /usr/include/iso/string_iso.h
obj/verify.o: ../simple-4.4G/include/timing.h graph.h stack.h
