// Automatically generated by \RMF\Eclipse\Workspaces\safari\x10.common\bin/makeTestCompiler 
// Do not edit
/*
 * Generated by rfuhrer on Aug 4, 2006
 */
package polyglot.ext.x10.tests;

import junit.framework.TestSuite;

/**
 * @author vj Jan 11, 2005
 */
public class TestCompiler extends TestX10_Compiler {

	/**
	 * @param name
	 */
	public TestCompiler(String name) {
		super(name);
	}

	public void test_Applications_NewJavaGrande_crypt_distributed_JGFCryptBenchSizeA() {
		//run("./JGFCryptBenchSizeA.x10","JGFCryptBenchSizeA","./Applications/NewJavaGrande/crypt/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_crypt_parallel_JGFCryptBenchSizeA() {
		//run("./JGFCryptBenchSizeA.x10","JGFCryptBenchSizeA","./Applications/NewJavaGrande/crypt/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_crypt_serial_JGFCryptBenchSizeA() {
		//run("./JGFCryptBenchSizeA.x10","JGFCryptBenchSizeA","./Applications/NewJavaGrande/crypt/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_lufact_distributed_JGFLUFactBenchSizeA() {
		//run("./JGFLUFactBenchSizeA.x10","JGFLUFactBenchSizeA","./Applications/NewJavaGrande/lufact/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_lufact_parallel_JGFLUFactBenchSizeA() {
		//run("./JGFLUFactBenchSizeA.x10","JGFLUFactBenchSizeA","./Applications/NewJavaGrande/lufact/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_lufact_serial_JGFLUFactBenchSizeA() {
		//run("./JGFLUFactBenchSizeA.x10","JGFLUFactBenchSizeA","./Applications/NewJavaGrande/lufact/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_moldyn_distributed_JGFMolDynBenchSizeA() {
		//run("./JGFMolDynBenchSizeA.x10","JGFMolDynBenchSizeA","./Applications/NewJavaGrande/moldyn/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_moldyn_parallel_JGFMolDynBenchSizeA() {
		//run("./JGFMolDynBenchSizeA.x10","JGFMolDynBenchSizeA","./Applications/NewJavaGrande/moldyn/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_moldyn_serial_JGFMolDynBenchSizeA() {
		//run("./JGFMolDynBenchSizeA.x10","JGFMolDynBenchSizeA","./Applications/NewJavaGrande/moldyn/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_montecarlo_distributed_JGFMonteCarloBenchSizeA() {
		//run("./JGFMonteCarloBenchSizeA.x10","JGFMonteCarloBenchSizeA","./Applications/NewJavaGrande/montecarlo/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_montecarlo_parallel_JGFMonteCarloBenchSizeA() {
		//run("./JGFMonteCarloBenchSizeA.x10","JGFMonteCarloBenchSizeA","./Applications/NewJavaGrande/montecarlo/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_montecarlo_serial_JGFMonteCarloBenchSizeA() {
		//run("./JGFMonteCarloBenchSizeA.x10","JGFMonteCarloBenchSizeA","./Applications/NewJavaGrande/montecarlo/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_raytracer_distributed_JGFRayTracerBenchSizeA() {
		//run("./JGFRayTracerBenchSizeA.x10","JGFRayTracerBenchSizeA","./Applications/NewJavaGrande/raytracer/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_raytracer_parallel_JGFRayTracerBenchSizeA() {
		//run("./JGFRayTracerBenchSizeA.x10","JGFRayTracerBenchSizeA","./Applications/NewJavaGrande/raytracer/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_raytracer_serial_JGFRayTracerBenchSizeA() {
		//run("./JGFRayTracerBenchSizeA.x10","JGFRayTracerBenchSizeA","./Applications/NewJavaGrande/raytracer/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_series_distributed_JGFSeriesBenchSizeA() {
		//run("./JGFSeriesBenchSizeA.x10","JGFSeriesBenchSizeA","./Applications/NewJavaGrande/series/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_series_parallel_JGFSeriesBenchSizeA() {
		//run("./JGFSeriesBenchSizeA.x10","JGFSeriesBenchSizeA","./Applications/NewJavaGrande/series/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_series_serial_JGFSeriesBenchSizeA() {
		//run("./JGFSeriesBenchSizeA.x10","JGFSeriesBenchSizeA","./Applications/NewJavaGrande/series/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sor_distributed_JGFSORBenchSizeA() {
		//run("./JGFSORBenchSizeA.x10","JGFSORBenchSizeA","./Applications/NewJavaGrande/sor/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sor_parallel_JGFSORBenchSizeA() {
		//run("./JGFSORBenchSizeA.x10","JGFSORBenchSizeA","./Applications/NewJavaGrande/sor/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sor_serial_JGFSORBenchSizeA() {
		//run("./JGFSORBenchSizeA.x10","JGFSORBenchSizeA","./Applications/NewJavaGrande/sor/serial");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sparsematmult_distributed_JGFSparseMatmultBenchSizeA() {
		//run("./JGFSparseMatmultBenchSizeA.x10","JGFSparseMatmultBenchSizeA","./Applications/NewJavaGrande/sparsematmult/distributed");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sparsematmult_parallel_JGFSparseMatmultBenchSizeA() {
		//run("./JGFSparseMatmultBenchSizeA.x10","JGFSparseMatmultBenchSizeA","./Applications/NewJavaGrande/sparsematmult/parallel");
		runHelper();
	}

	public void test_Applications_NewJavaGrande_sparsematmult_serial_JGFSparseMatmultBenchSizeA() {
		//run("./JGFSparseMatmultBenchSizeA.x10","JGFSparseMatmultBenchSizeA","./Applications/NewJavaGrande/sparsematmult/serial");
		runHelper();
	}

	public void test_Applications_NPB3$0_cg() {
		//run("./cg.x10","cg","./Applications/NPB3_0");
		runHelper();
	}

	public void test_Applications_NPB3$0_mg() {
		//run("./mg.x10","mg","./Applications/NPB3_0");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel1() {
		//run("./Edmiston_Parallel1.x10","Edmiston_Parallel1","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel10() {
		//run("./Edmiston_Parallel10.x10","Edmiston_Parallel10","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel11() {
		//run("./Edmiston_Parallel11.x10","Edmiston_Parallel11","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel2() {
		//run("./Edmiston_Parallel2.x10","Edmiston_Parallel2","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel3() {
		//run("./Edmiston_Parallel3.x10","Edmiston_Parallel3","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel4() {
		//run("./Edmiston_Parallel4.x10","Edmiston_Parallel4","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel4b() {
		//run("./Edmiston_Parallel4b.x10","Edmiston_Parallel4b","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel5() {
		//run("./Edmiston_Parallel5.x10","Edmiston_Parallel5","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel6() {
		//run("./Edmiston_Parallel6.x10","Edmiston_Parallel6","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel7() {
		//run("./Edmiston_Parallel7.x10","Edmiston_Parallel7","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel8() {
		//run("./Edmiston_Parallel8.x10","Edmiston_Parallel8","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Parallel9() {
		//run("./Edmiston_Parallel9.x10","Edmiston_Parallel9","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Sequential1() {
		//run("./Edmiston_Sequential1.x10","Edmiston_Sequential1","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Sequential2() {
		//run("./Edmiston_Sequential2.x10","Edmiston_Sequential2","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Edmiston$Sequential3() {
		//run("./Edmiston_Sequential3.x10","Edmiston_Sequential3","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_GameOfLife() {
		//run("./GameOfLife.x10","GameOfLife","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Jacobi() {
		//run("./Jacobi.x10","Jacobi","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_JacobiSmall() {
		//run("./JacobiSmall.x10","JacobiSmall","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Jacobi$skewed() {
		//run("./Jacobi_skewed.x10","Jacobi_skewed","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_MpiExample() {
		//run("./MpiExample.x10","MpiExample","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_MpiExample2() {
		//run("./MpiExample2.x10","MpiExample2","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_QueensList() {
		//run("./QueensList.x10","QueensList","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_QueensList3() {
		//run("./QueensList3.x10","QueensList3","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_RandomAccess() {
		//run("./RandomAccess.x10","RandomAccess","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_RandomAccess$int() {
		//run("./RandomAccess_int.x10","RandomAccess_int","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_RandomAccess$long() {
		//run("./RandomAccess_long.x10","RandomAccess_long","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_RandomAccess$skewed() {
		//run("./RandomAccess_skewed.x10","RandomAccess_skewed","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_OtherApps_Tree() {
		//run("./Tree.x10","Tree","./Applications/OtherApps");
		runHelper();
	}

	public void test_Applications_sparsematmult_SparseMatmultAllValues() {
		//run("./SparseMatmultAllValues.x10","SparseMatmultAllValues","./Applications/sparsematmult");
		runHelper();
	}

	public void test_Applications_sparsematmult_SparseMatmultAllValuesClean() {
		//run("./SparseMatmultAllValuesClean.x10","SparseMatmultAllValuesClean","./Applications/sparsematmult");
		runHelper();
	}

	public void test_Constructs_Array_Array1() {
		//run("./Array1.x10","Array1","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array1b() {
		//run("./Array1b.x10","Array1b","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array1c() {
		//run("./Array1c.x10","Array1c","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array1Exploded() {
		//run("./Array1Exploded.x10","Array1Exploded","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array2v() {
		//run("./Array2v.x10","Array2v","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3() {
		//run("./Array3.x10","Array3","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array31() {
		//run("./Array31.x10","Array31","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Boolean() {
		//run("./Array3Boolean.x10","Array3Boolean","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Byte() {
		//run("./Array3Byte.x10","Array3Byte","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Char() {
		//run("./Array3Char.x10","Array3Char","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Double() {
		//run("./Array3Double.x10","Array3Double","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Float() {
		//run("./Array3Float.x10","Array3Float","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Long() {
		//run("./Array3Long.x10","Array3Long","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array3Short() {
		//run("./Array3Short.x10","Array3Short","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array4() {
		//run("./Array4.x10","Array4","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_Array5() {
		//run("./Array5.x10","Array5","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayAlgebra() {
		//run("./ArrayAlgebra.x10","ArrayAlgebra","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayAlgebra2() {
		//run("./ArrayAlgebra2.x10","ArrayAlgebra2","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayArrayInitializerShorthand() {
		//run("./ArrayArrayInitializerShorthand.x10","ArrayArrayInitializerShorthand","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayBounds1D() {
		//run("./ArrayBounds1D.x10","ArrayBounds1D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayBounds2D() {
		//run("./ArrayBounds2D.x10","ArrayBounds2D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayBounds3D() {
		//run("./ArrayBounds3D.x10","ArrayBounds3D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayCopy1() {
		//run("./ArrayCopy1.x10","ArrayCopy1","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayCopy2() {
		//run("./ArrayCopy2.x10","ArrayCopy2","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayCopy3() {
		//run("./ArrayCopy3.x10","ArrayCopy3","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayDecl() {
		//run("./ArrayDecl.x10","ArrayDecl","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayFuture() {
		//run("./ArrayFuture.x10","ArrayFuture","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayInitializer() {
		//run("./ArrayInitializer.x10","ArrayInitializer","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayInitializerShorthand() {
		//run("./ArrayInitializerShorthand.x10","ArrayInitializerShorthand","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayOpAssign() {
		//run("./ArrayOpAssign.x10","ArrayOpAssign","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayOpAssign2() {
		//run("./ArrayOpAssign2.x10","ArrayOpAssign2","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayOverRegion() {
		//run("./ArrayOverRegion.x10","ArrayOverRegion","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ArrayTypeCheck() {
		//run("./ArrayTypeCheck.x10","ArrayTypeCheck","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ConstructDist2D() {
		//run("./ConstructDist2D.x10","ConstructDist2D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_IntArrayInitializerShorthand() {
		//run("./IntArrayInitializerShorthand.x10","IntArrayInitializerShorthand","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_IntArrayMaxAbs() {
		//run("./IntArrayMaxAbs.x10","IntArrayMaxAbs","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_IntValueArrayInitializerShorthand() {
		//run("./IntValueArrayInitializerShorthand.x10","IntValueArrayInitializerShorthand","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_JavaArrayInitializer$MustFailCompile() {
		//run("./JavaArrayInitializer_MustFailCompile.x10","JavaArrayInitializer_MustFailCompile","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_MiscTest1() {
		//run("./MiscTest1.x10","MiscTest1","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_MultiDimensionalJavaArray() {
		//run("./MultiDimensionalJavaArray.x10","MultiDimensionalJavaArray","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_NullableArrayAssign() {
		//run("./NullableArrayAssign.x10","NullableArrayAssign","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_ObjectArrayInitializerShorthand() {
		//run("./ObjectArrayInitializerShorthand.x10","ObjectArrayInitializerShorthand","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_UserArrayBounds1D() {
		//run("./UserArrayBounds1D.x10","UserArrayBounds1D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_UserArrayBounds2D() {
		//run("./UserArrayBounds2D.x10","UserArrayBounds2D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_UserArrayBounds3D() {
		//run("./UserArrayBounds3D.x10","UserArrayBounds3D","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Array_UserDefinedArray() {
		//run("./UserDefinedArray.x10","UserDefinedArray","./Constructs/Array");
		runHelper();
	}

	public void test_Constructs_Async_AsyncFieldAccess() {
		//run("./AsyncFieldAccess.x10","AsyncFieldAccess","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncNext() {
		//run("./AsyncNext.x10","AsyncNext","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncReturn() {
		//run("./AsyncReturn.x10","AsyncReturn","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest() {
		//run("./AsyncTest.x10","AsyncTest","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest1() {
		//run("./AsyncTest1.x10","AsyncTest1","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest2() {
		//run("./AsyncTest2.x10","AsyncTest2","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest3$MustFailRun() {
		//run("./AsyncTest3_MustFailRun.x10","AsyncTest3_MustFailRun","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest4$MustFailCompile() {
		//run("./AsyncTest4_MustFailCompile.x10","AsyncTest4_MustFailCompile","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_AsyncTest5() {
		//run("./AsyncTest5.x10","AsyncTest5","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_ClockAsyncTest() {
		//run("./ClockAsyncTest.x10","ClockAsyncTest","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_Async_ClockAsyncTest2() {
		//run("./ClockAsyncTest2.x10","ClockAsyncTest2","./Constructs/Async");
		runHelper();
	}

	public void test_Constructs_AtEach_AtEach() {
		//run("./AtEach.x10","AtEach","./Constructs/AtEach");
		runHelper();
	}

	public void test_Constructs_AtEach_AtEach2() {
		//run("./AtEach2.x10","AtEach2","./Constructs/AtEach");
		runHelper();
	}

	public void test_Constructs_AtEach_AtEachLoopOnArray() {
		//run("./AtEachLoopOnArray.x10","AtEachLoopOnArray","./Constructs/AtEach");
		runHelper();
	}

	public void test_Constructs_Atomic_Atomic1() {
		//run("./Atomic1.x10","Atomic1","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_Atomic2() {
		//run("./Atomic2.x10","Atomic2","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AtomicContainingWhen$MustFailRun() {
		//run("./AtomicContainingWhen_MustFailRun.x10","AtomicContainingWhen_MustFailRun","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AtomicMethodTest() {
		//run("./AtomicMethodTest.x10","AtomicMethodTest","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AtomicOrdered() {
		//run("./AtomicOrdered.x10","AtomicOrdered","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AtomicReturn() {
		//run("./AtomicReturn.x10","AtomicReturn","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AtomicTest() {
		//run("./AtomicTest.x10","AtomicTest","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AwaitTest() {
		//run("./AwaitTest.x10","AwaitTest","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_AwaitTest2() {
		//run("./AwaitTest2.x10","AwaitTest2","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_ConditionalAtomicQueue() {
		//run("./ConditionalAtomicQueue.x10","ConditionalAtomicQueue","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_ConditionalAtomicTest() {
		//run("./ConditionalAtomicTest.x10","ConditionalAtomicTest","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_WhenReturn() {
		//run("./WhenReturn.x10","WhenReturn","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Atomic_WhenReturnAll() {
		//run("./WhenReturnAll.x10","WhenReturnAll","./Constructs/Atomic");
		runHelper();
	}

	public void test_Constructs_Boxing_Boxing0() {
		//run("./Boxing0.x10","Boxing0","./Constructs/Boxing");
		runHelper();
	}

	public void test_Constructs_Boxing_Boxing1() {
		//run("./Boxing1.x10","Boxing1","./Constructs/Boxing");
		runHelper();
	}

	public void test_Constructs_Boxing_Boxing2() {
		//run("./Boxing2.x10","Boxing2","./Constructs/Boxing");
		runHelper();
	}

	public void test_Constructs_Clock_ClockFuture() {
		//run("./ClockFuture.x10","ClockFuture","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockPascal() {
		//run("./ClockPascal.x10","ClockPascal","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockPascal2() {
		//run("./ClockPascal2.x10","ClockPascal2","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest() {
		//run("./ClockTest.x10","ClockTest","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest1() {
		//run("./ClockTest1.x10","ClockTest1","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest10() {
		//run("./ClockTest10.x10","ClockTest10","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest10a() {
		//run("./ClockTest10a.x10","ClockTest10a","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest11$MustFailRun() {
		//run("./ClockTest11_MustFailRun.x10","ClockTest11_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest12() {
		//run("./ClockTest12.x10","ClockTest12","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest13() {
		//run("./ClockTest13.x10","ClockTest13","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest14() {
		//run("./ClockTest14.x10","ClockTest14","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest15() {
		//run("./ClockTest15.x10","ClockTest15","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest15WithResume() {
		//run("./ClockTest15WithResume.x10","ClockTest15WithResume","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest16a$MustFailRun() {
		//run("./ClockTest16a_MustFailRun.x10","ClockTest16a_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest16$MustFailRun() {
		//run("./ClockTest16_MustFailRun.x10","ClockTest16_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest17$MustFailRun() {
		//run("./ClockTest17_MustFailRun.x10","ClockTest17_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest18$MustFailRun() {
		//run("./ClockTest18_MustFailRun.x10","ClockTest18_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest2() {
		//run("./ClockTest2.x10","ClockTest2","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest3() {
		//run("./ClockTest3.x10","ClockTest3","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest3a() {
		//run("./ClockTest3a.x10","ClockTest3a","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest3b() {
		//run("./ClockTest3b.x10","ClockTest3b","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest4() {
		//run("./ClockTest4.x10","ClockTest4","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest5() {
		//run("./ClockTest5.x10","ClockTest5","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest6() {
		//run("./ClockTest6.x10","ClockTest6","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest7$MustFailRun() {
		//run("./ClockTest7_MustFailRun.x10","ClockTest7_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest8$MustFailRun() {
		//run("./ClockTest8_MustFailRun.x10","ClockTest8_MustFailRun","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Clock_ClockTest9() {
		//run("./ClockTest9.x10","ClockTest9","./Constructs/Clock");
		runHelper();
	}

	public void test_Constructs_Distribution_ArrayToDist() {
		//run("./ArrayToDist.x10","ArrayToDist","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_BlockCyclicDist() {
		//run("./BlockCyclicDist.x10","BlockCyclicDist","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_BlockCyclicDistWithPlaceSet() {
		//run("./BlockCyclicDistWithPlaceSet.x10","BlockCyclicDistWithPlaceSet","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_BlockDist() {
		//run("./BlockDist.x10","BlockDist","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_BlockDistWithPlaceSet() {
		//run("./BlockDistWithPlaceSet.x10","BlockDistWithPlaceSet","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_CyclicDist() {
		//run("./CyclicDist.x10","CyclicDist","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_CyclicDistWithPlaceSet() {
		//run("./CyclicDistWithPlaceSet.x10","CyclicDistWithPlaceSet","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistAlgebra() {
		//run("./DistAlgebra.x10","DistAlgebra","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistAlgebra2() {
		//run("./DistAlgebra2.x10","DistAlgebra2","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistAlgebra3$MustFailRun() {
		//run("./DistAlgebra3_MustFailRun.x10","DistAlgebra3_MustFailRun","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistBounds1D() {
		//run("./DistBounds1D.x10","DistBounds1D","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistBounds2D() {
		//run("./DistBounds2D.x10","DistBounds2D","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistBounds3D() {
		//run("./DistBounds3D.x10","DistBounds3D","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistributionTest() {
		//run("./DistributionTest.x10","DistributionTest","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_DistributionTest1() {
		//run("./DistributionTest1.x10","DistributionTest1","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Distribution_Restrict() {
		//run("./Restrict.x10","Restrict","./Constructs/Distribution");
		runHelper();
	}

	public void test_Constructs_Exceptions_ExceptionBug$MustFailRun() {
		//run("./ExceptionBug_MustFailRun.x10","ExceptionBug_MustFailRun","./Constructs/Exceptions");
		runHelper();
	}

	public void test_Constructs_Exceptions_Exceptions() {
		//run("./Exceptions.x10","Exceptions","./Constructs/Exceptions");
		runHelper();
	}

	public void test_Constructs_Exceptions_Exceptions2() {
		//run("./Exceptions2.x10","Exceptions2","./Constructs/Exceptions");
		runHelper();
	}

	public void test_Constructs_Exceptions_Exceptions$BadPlace() {
		//run("./Exceptions_BadPlace.x10","Exceptions_BadPlace","./Constructs/Exceptions");
		runHelper();
	}

	public void test_Constructs_Extern_BasicExternTest1() {
		//run("./BasicExternTest1.x10","BasicExternTest1","./Constructs/Extern");
		runHelper();
	}

	public void test_Constructs_Extern_IntArrayExternUnsafe() {
		//run("./IntArrayExternUnsafe.x10","IntArrayExternUnsafe","./Constructs/Extern");
		runHelper();
	}

	public void test_Constructs_Extern_JacobiExtern() {
		//run("./JacobiExtern.x10","JacobiExtern","./Constructs/Extern");
		runHelper();
	}

	public void test_Constructs_Extern_RandomAccess$longExtern() {
		//run("./RandomAccess_longExtern.x10","RandomAccess_longExtern","./Constructs/Extern");
		runHelper();
	}

	public void test_Constructs_Final_ImplicitFinal() {
		//run("./ImplicitFinal.x10","ImplicitFinal","./Constructs/Final");
		runHelper();
	}

	public void test_Constructs_Final_ImplicitFinal2() {
		//run("./ImplicitFinal2.x10","ImplicitFinal2","./Constructs/Final");
		runHelper();
	}

	public void test_Constructs_Finish_FinishTest1() {
		//run("./FinishTest1.x10","FinishTest1","./Constructs/Finish");
		runHelper();
	}

	public void test_Constructs_Finish_FinishTest2() {
		//run("./FinishTest2.x10","FinishTest2","./Constructs/Finish");
		runHelper();
	}

	public void test_Constructs_For_ForLoop() {
		//run("./ForLoop.x10","ForLoop","./Constructs/For");
		runHelper();
	}

	public void test_Constructs_For_ForLoop2() {
		//run("./ForLoop2.x10","ForLoop2","./Constructs/For");
		runHelper();
	}

	public void test_Constructs_For_ForLoop3() {
		//run("./ForLoop3.x10","ForLoop3","./Constructs/For");
		runHelper();
	}

	public void test_Constructs_For_ForLoop4() {
		//run("./ForLoop4.x10","ForLoop4","./Constructs/For");
		runHelper();
	}

	public void test_Constructs_For_ForLoopOnArray() {
		//run("./ForLoopOnArray.x10","ForLoopOnArray","./Constructs/For");
		runHelper();
	}

	public void test_Constructs_ForEach_Foreach1() {
		//run("./Foreach1.x10","Foreach1","./Constructs/ForEach");
		runHelper();
	}

	public void test_Constructs_ForEach_Foreach2() {
		//run("./Foreach2.x10","Foreach2","./Constructs/ForEach");
		runHelper();
	}

	public void test_Constructs_Future_Future0() {
		//run("./Future0.x10","Future0","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future1() {
		//run("./Future1.x10","Future1","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future1Boxed() {
		//run("./Future1Boxed.x10","Future1Boxed","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future2Boxed() {
		//run("./Future2Boxed.x10","Future2Boxed","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future3() {
		//run("./Future3.x10","Future3","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future3Boxed() {
		//run("./Future3Boxed.x10","Future3Boxed","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future4() {
		//run("./Future4.x10","Future4","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_Future4Boxed() {
		//run("./Future4Boxed.x10","Future4Boxed","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureForce() {
		//run("./FutureForce.x10","FutureForce","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureNullable0() {
		//run("./FutureNullable0.x10","FutureNullable0","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureNullable1Boxed() {
		//run("./FutureNullable1Boxed.x10","FutureNullable1Boxed","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureTest2() {
		//run("./FutureTest2.x10","FutureTest2","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureTest3() {
		//run("./FutureTest3.x10","FutureTest3","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureTest4$MustFailCompile() {
		//run("./FutureTest4_MustFailCompile.x10","FutureTest4_MustFailCompile","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Future_FutureTest5() {
		//run("./FutureTest5.x10","FutureTest5","./Constructs/Future");
		runHelper();
	}

	public void test_Constructs_Import_ClassPathTest() {
		//run("./ClassPathTest.x10","ClassPathTest","./Constructs/Import");
		runHelper();
	}

	public void test_Constructs_Import_ImportTest() {
		//run("./ImportTest.x10","ImportTest","./Constructs/Import");
		runHelper();
	}

	public void test_Constructs_Import_ImportTestPackage1_SubPackage_T3() {
		//run("ImportTestPackage1/SubPackage/T3.x10","ImportTestPackage1.SubPackage.T3","./Constructs/Import");
		runHelper();
	}

	public void test_Constructs_Init_InitNonNullable$MustFailCompile() {
		//run("./InitNonNullable_MustFailCompile.x10","InitNonNullable_MustFailCompile","./Constructs/Init");
		runHelper();
	}

	public void test_Constructs_NoStaticMutable_NoStaticMutable1$MustFailCompile() {
		//run("./NoStaticMutable1_MustFailCompile.x10","NoStaticMutable1_MustFailCompile","./Constructs/NoStaticMutable");
		runHelper();
	}

	public void test_Constructs_Nullable_DoubleToNullableDoubleCastTest() {
		//run("./DoubleToNullableDoubleCastTest.x10","DoubleToNullableDoubleCastTest","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_DoubleToNullableDoubleTest() {
		//run("./DoubleToNullableDoubleTest.x10","DoubleToNullableDoubleTest","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_Nullable0Ref() {
		//run("./Nullable0Ref.x10","Nullable0Ref","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_Nullable1() {
		//run("./Nullable1.x10","Nullable1","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_Nullable2() {
		//run("./Nullable2.x10","Nullable2","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_Nullable5() {
		//run("./Nullable5.x10","Nullable5","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableArray() {
		//run("./NullableArray.x10","NullableArray","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableArray2() {
		//run("./NullableArray2.x10","NullableArray2","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableArray3$MustFailCompile() {
		//run("./NullableArray3_MustFailCompile.x10","NullableArray3_MustFailCompile","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableArray4() {
		//run("./NullableArray4.x10","NullableArray4","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableFuture0() {
		//run("./NullableFuture0.x10","NullableFuture0","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableFuture1() {
		//run("./NullableFuture1.x10","NullableFuture1","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableFuture2() {
		//run("./NullableFuture2.x10","NullableFuture2","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableInt() {
		//run("./NullableInt.x10","NullableInt","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableIntArray() {
		//run("./NullableIntArray.x10","NullableIntArray","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableObject() {
		//run("./NullableObject.x10","NullableObject","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableObject2() {
		//run("./NullableObject2.x10","NullableObject2","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableObject3() {
		//run("./NullableObject3.x10","NullableObject3","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_Nullable_NullableOverriding() {
		//run("./NullableOverriding.x10","NullableOverriding","./Constructs/Nullable");
		runHelper();
	}

	public void test_Constructs_PlaceCast_ClassCast1() {
		//run("./ClassCast1.x10","ClassCast1","./Constructs/PlaceCast");
		runHelper();
	}

	public void test_Constructs_PlaceCast_PlaceCast() {
		//run("./PlaceCast.x10","PlaceCast","./Constructs/PlaceCast");
		runHelper();
	}

	public void test_Constructs_PlaceCast_PlaceCast2() {
		//run("./PlaceCast2.x10","PlaceCast2","./Constructs/PlaceCast");
		runHelper();
	}

	public void test_Constructs_PlaceCast_PlaceCheck1() {
		//run("./PlaceCheck1.x10","PlaceCheck1","./Constructs/PlaceCast");
		runHelper();
	}

	public void test_Constructs_Point_ArrayPointBinding$MustFailCompile() {
		//run("./ArrayPointBinding_MustFailCompile.x10","ArrayPointBinding_MustFailCompile","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_PointArithmetic() {
		//run("./PointArithmetic.x10","PointArithmetic","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_PointArray() {
		//run("./PointArray.x10","PointArray","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_PointBinding() {
		//run("./PointBinding.x10","PointBinding","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_PointIndex() {
		//run("./PointIndex.x10","PointIndex","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_PointRebinding() {
		//run("./PointRebinding.x10","PointRebinding","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Point_UninitializedPointBinding$MustFailCompile() {
		//run("./UninitializedPointBinding_MustFailCompile.x10","UninitializedPointBinding_MustFailCompile","./Constructs/Point");
		runHelper();
	}

	public void test_Constructs_Region_ArrayOfRegions() {
		//run("./ArrayOfRegions.x10","ArrayOfRegions","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionAlgebra() {
		//run("./RegionAlgebra.x10","RegionAlgebra","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionBanded() {
		//run("./RegionBanded.x10","RegionBanded","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionConvexHull() {
		//run("./RegionConvexHull.x10","RegionConvexHull","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionTest1() {
		//run("./RegionTest1.x10","RegionTest1","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionTest2() {
		//run("./RegionTest2.x10","RegionTest2","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionTestIterator() {
		//run("./RegionTestIterator.x10","RegionTestIterator","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionTriangular() {
		//run("./RegionTriangular.x10","RegionTriangular","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionWithHoles() {
		//run("./RegionWithHoles.x10","RegionWithHoles","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_Region_RegionWithHoles2() {
		//run("./RegionWithHoles2.x10","RegionWithHoles2","./Constructs/Region");
		runHelper();
	}

	public void test_Constructs_StorageClass_StorageClassesTest() {
		//run("./StorageClassesTest.x10","StorageClassesTest","./Constructs/StorageClass");
		runHelper();
	}

	public void test_Constructs_Unsafe_Unsafe() {
		//run("./Unsafe.x10","Unsafe","./Constructs/Unsafe");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass() {
		//run("./ValueClass.x10","ValueClass","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass2$MustFailCompile() {
		//run("./ValueClass2_MustFailCompile.x10","ValueClass2_MustFailCompile","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass3$MustFailCompile() {
		//run("./ValueClass3_MustFailCompile.x10","ValueClass3_MustFailCompile","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass4() {
		//run("./ValueClass4.x10","ValueClass4","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass5$MustFailCompile() {
		//run("./ValueClass5_MustFailCompile.x10","ValueClass5_MustFailCompile","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueClass6() {
		//run("./ValueClass6.x10","ValueClass6","./Constructs/Value");
		runHelper();
	}

	public void test_Constructs_Value_ValueEquality() {
		//run("./ValueEquality.x10","ValueEquality","./Constructs/Value");
		runHelper();
	}

	public void test_Misc_BreakInForTest() {
		//run("./BreakInForTest.x10","BreakInForTest","./Misc");
		runHelper();
	}

	public void test_Misc_CommentTest() {
		//run("./CommentTest.x10","CommentTest","./Misc");
		runHelper();
	}

	public void test_Misc_DepType() {
		//run("./DepType.x10","DepType","./Misc");
		runHelper();
	}

	public void test_Misc_ExpressionParentheses() {
		//run("./ExpressionParentheses.x10","ExpressionParentheses","./Misc");
		runHelper();
	}

	public void test_Misc_FieldAccessTest() {
		//run("./FieldAccessTest.x10","FieldAccessTest","./Misc");
		runHelper();
	}

	public void test_Misc_FinalInitializationTest() {
		//run("./FinalInitializationTest.x10","FinalInitializationTest","./Misc");
		runHelper();
	}

	public void test_Misc_HereParentheses() {
		//run("./HereParentheses.x10","HereParentheses","./Misc");
		runHelper();
	}

	public void test_Misc_IfElseFinishBug() {
		//run("./IfElseFinishBug.x10","IfElseFinishBug","./Misc");
		runHelper();
	}

	public void test_Misc_InfiniteLoopTest$MustFailTimeout() {
	    runHelper();
	}

	public void test_Misc_ListTest() {
		//run("./ListTest.x10","ListTest","./Misc");
		runHelper();
	}

	public void test_Misc_LiteralTest() {
		//run("./LiteralTest.x10","LiteralTest","./Misc");
		runHelper();
	}

	public void test_Misc_MissingReturn$MustFailCompile() {
		//run("./MissingReturn_MustFailCompile.x10","MissingReturn_MustFailCompile","./Misc");
		runHelper();
	}

	public void test_Misc_NonX10Constructs$MustFailCompile() {
		//run("./NonX10Constructs_MustFailCompile.x10","NonX10Constructs_MustFailCompile","./Misc");
		runHelper();
	}

	public void test_Misc_NopTest() {
		//run("./NopTest.x10","NopTest","./Misc");
		runHelper();
	}

	public void test_Misc_NullableComparison() {
		//run("./NullableComparison.x10","NullableComparison","./Misc");
		runHelper();
	}

	public void test_Misc_ObjectEquality() {
		//run("./ObjectEquality.x10","ObjectEquality","./Misc");
		runHelper();
	}

	public void test_Misc_RemoteAccessCheck() {
		//run("./RemoteAccessCheck.x10","RemoteAccessCheck","./Misc");
		runHelper();
	}

	public void test_Misc_SevereError$MustFailRun() {
		//run("./SevereError_MustFailRun.x10","SevereError_MustFailRun","./Misc");
		runHelper();
	}

	public void test_Misc_StringTest() {
		//run("./StringTest.x10","StringTest","./Misc");
		runHelper();
	}

	public void test_Misc_TabsInStrings() {
		//run("./TabsInStrings.x10","TabsInStrings","./Misc");
		runHelper();
	}

	public void test_Misc_Unreachable() {
		//run("./Unreachable.x10","Unreachable","./Misc");
		runHelper();
	}

	public void test_Misc_VariableScope() {
		//run("./VariableScope.x10","VariableScope","./Misc");
		runHelper();
	}

	public void test_Timings_ArrayIndexing() {
		//run("./ArrayIndexing.x10","ArrayIndexing","./Timings");
		runHelper();
	}

	public void test_Timings_Initialization() {
		//run("./Initialization.x10","Initialization","./Timings");
		runHelper();
	}

	public void test_Timings_IntArrayIndexing() {
		//run("./IntArrayIndexing.x10","IntArrayIndexing","./Timings");
		runHelper();
	}

	public void test_x10lib_TestHarness() {
		//run("./TestHarness.x10","TestHarness","./x10lib");
		runHelper();
	}

	public static void main(String args[]) {
		TestX10_Compiler.Main(TestCompiler.class);
	}

	public static TestSuite suite() {
		return TestX10_Compiler.suite(TestCompiler.class);
	}
}

