EXECS = span 

SIMPLE_DIR = ../simple-4.4G

OPT         = -O$(O_LEVEL)
# OPT       = -g

include ./Makefile.smp.mk

# DO NOT DELETE

obj/init.o: /usr/include/stdio.h /usr/include/standards.h
obj/init.o: /usr/include/va_list.h /usr/include/sys/types.h
obj/init.o: /usr/include/strict_stdtypes.h /usr/include/sys/inttypes.h
obj/init.o: /usr/include/stdint.h /usr/include/end_strict_stdtypes.h
obj/init.o: /usr/include/sys/m_types.h /usr/include/sys/vm_types.h
obj/init.o: /usr/include/sys/limits.h /usr/include/float.h
obj/init.o: /usr/include/stdlib.h /usr/include/sys/wait.h
obj/init.o: /usr/include/sys/resource.h /usr/include/sys/time.h
obj/init.o: /usr/include/sys/signal.h /usr/include/sys/context.h
obj/init.o: /usr/include/sys/m_param.h /usr/include/sys/mstsave.h
obj/init.o: /usr/include/sys/m_signal.h /usr/include/sys/localedef.h
obj/init.o: /usr/include/sys/lc_core.h /usr/include/locale.h
obj/init.o: /usr/include/sys/localedef31.h graph.h
obj/lock.o: lock.h /usr/include/pthread.h /usr/include/standards.h
obj/lock.o: /usr/include/strict_stdtypes.h /usr/include/sys/types.h
obj/lock.o: /usr/include/sys/inttypes.h /usr/include/stdint.h
obj/lock.o: /usr/include/end_strict_stdtypes.h /usr/include/sys/m_types.h
obj/lock.o: /usr/include/sys/vm_types.h /usr/include/time.h
obj/lock.o: /usr/include/stddef.h /usr/include/sched.h
obj/lock.o: /usr/include/sys/sched.h /usr/include/sys/pri.h
obj/lock.o: /usr/include/sys/proc.h /usr/include/sys/ptrace.h
obj/lock.o: /usr/include/sys/thread.h /usr/include/sys/mstsave.h
obj/lock.o: /usr/include/sys/m_param.h /usr/include/sys/processor.h
obj/lock.o: /usr/include/sys/lock_def.h /usr/include/sys/var.h
obj/lock.o: /usr/include/sys/atomic_op.h /usr/include/sys/context.h
obj/lock.o: /usr/include/sys/time.h /usr/include/sys/timer.h
obj/lock.o: /usr/include/sys/cred.h /usr/include/sys/limits.h
obj/lock.o: /usr/include/float.h /usr/include/sys/priv.h
obj/lock.o: /usr/include/sys/mode.h /usr/include/sys/tcb.h
obj/lock.o: /usr/include/sys/pcl.h /usr/include/sys/lockl.h
obj/lock.o: /usr/include/sys/capabilities.h /usr/include/sys/resource.h
obj/lock.o: /usr/include/unistd.h /usr/include/sys/access.h
obj/lock.o: /usr/include/sys/lockf.h
obj/r_graph.o: /usr/include/stdio.h /usr/include/standards.h
obj/r_graph.o: /usr/include/va_list.h /usr/include/sys/types.h
obj/r_graph.o: /usr/include/strict_stdtypes.h /usr/include/sys/inttypes.h
obj/r_graph.o: /usr/include/stdint.h /usr/include/end_strict_stdtypes.h
obj/r_graph.o: /usr/include/sys/m_types.h /usr/include/sys/vm_types.h
obj/r_graph.o: /usr/include/sys/limits.h /usr/include/float.h
obj/r_graph.o: /usr/include/stdlib.h /usr/include/sys/wait.h
obj/r_graph.o: /usr/include/sys/resource.h /usr/include/sys/time.h
obj/r_graph.o: /usr/include/sys/signal.h /usr/include/sys/context.h
obj/r_graph.o: /usr/include/sys/m_param.h /usr/include/sys/mstsave.h
obj/r_graph.o: /usr/include/sys/m_signal.h /usr/include/sys/localedef.h
obj/r_graph.o: /usr/include/sys/lc_core.h /usr/include/locale.h
obj/r_graph.o: /usr/include/sys/localedef31.h graph.h
obj/span.o: /usr/include/sys/types.h /usr/include/strict_stdtypes.h
obj/span.o: /usr/include/sys/inttypes.h /usr/include/stdint.h
obj/span.o: /usr/include/standards.h /usr/include/end_strict_stdtypes.h
obj/span.o: /usr/include/sys/m_types.h /usr/include/sys/vm_types.h graph.h
obj/span_CRCW.o: graph.h
obj/span_CRCW_lock.o: graph.h
obj/span_bfs.o: graph.h queue.h
obj/span_bfs_lb.o: graph.h queue.h
obj/span_bfs_spinlock.o: graph.h queue.h
obj/span_breadth_B1.o: graph.h stack.h
obj/span_breadth_B2.o: graph.h stack.h
obj/span_breadth_B3.o: graph.h stack.h
obj/span_breadth_cws.o: graph.h stack.h
