.TH "AsyncQueueEl" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsyncQueueEl \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fB_el\fP"
.br
.ti -1c
.RI "\fBAsyncQueueEl\fP * \fB_next\fP"
.br
.ti -1c
.RI "\fBAsyncQueueEl\fP * \fB_prev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBAsyncQueueEl::_el\fP"
.PP
.SS "struct \fBAsyncQueueEl\fP* \fBAsyncQueueEl::_next\fP"
.PP
.SS "struct \fBAsyncQueueEl\fP* \fBAsyncQueueEl::_prev\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
