.TH "__x10_normal_async_descr_t" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__x10_normal_async_descr_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBx10_finish_record_t\fP \fBfinish_record\fP"
.br
.ti -1c
.RI "\fBx10_place_t\fP \fBparent\fP"
.br
.ti -1c
.RI "size_t \fBcl_size\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t \fB__x10_normal_async_descr_t::cl_size\fP"
.PP
.SS "\fBx10_finish_record_t\fP \fB__x10_normal_async_descr_t::finish_record\fP"
.PP
.SS "\fBx10_place_t\fP \fB__x10_normal_async_descr_t::parent\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
