.TH "finish_compl_message_t" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
finish_compl_message_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtuple\fP * \fBtuples\fP"
.br
.ti -1c
.RI "int \fBnum_tuples\fP"
.br
.ti -1c
.RI "int \fBfinish_id\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBfinish_compl_message_t::finish_id\fP"
.PP
.SS "int \fBfinish_compl_message_t::num_tuples\fP"
.PP
.SS "\fBtuple\fP* \fBfinish_compl_message_t::tuples\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
