.TH "queue.cc" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'queue.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBx10_async_queue_t\fP \fBCreateQueue\fP ()"
.br
.ti -1c
.RI "void \fBDeleteQueue\fP (\fBx10_async_queue_t\fP q)"
.br
.ti -1c
.RI "void \fBPushQueue\fP (\fBx10_async_queue_t\fP q, void *element)"
.br
.ti -1c
.RI "\fBx10_async_queue_el_t\fP \fBPopQueue\fP (\fBx10_async_queue_t\fP q)"
.br
.ti -1c
.RI "void \fBRemoveQueue\fP (\fBx10_async_queue_t\fP q, \fBx10_async_queue_el_t\fP el)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBx10_async_queue_t\fP CreateQueue ()"
.PP
Implementation file for X10Lib's \fBAsyncQueue\fP interface. * 
.SS "void DeleteQueue (\fBx10_async_queue_t\fP q)"
.PP
.SS "\fBx10_async_queue_el_t\fP PopQueue (\fBx10_async_queue_t\fP q)"
.PP
.SS "void PushQueue (\fBx10_async_queue_t\fP q, void * element)"
.PP
.SS "void RemoveQueue (\fBx10_async_queue_t\fP q, \fBx10_async_queue_el_t\fP el)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
