.TH "x10_types.h" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x10_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBx10_finish_record_t\fP"
.br
.ti -1c
.RI "struct \fBx10_async_closure_t\fP"
.br
.ti -1c
.RI "struct \fBx10_comm_handle_t\fP"
.br
.ti -1c
.RI "struct \fBx10_clock_t\fP"
.br
.ti -1c
.RI "struct \fBx10_proxy_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEXTERN\fP"
.br
.ti -1c
.RI "#define \fBbool\fP   char"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned \fBx10_place_t\fP"
.br
.ti -1c
.RI "typedef unsigned \fBx10_async_handler_t\fP"
.br
.ti -1c
.RI "typedef \fBx10_proxy_t\fP \fBx10_remote_ref_t\fP"
.br
.ti -1c
.RI "typedef unsigned \fBx10_condition_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBx10_err_t\fP { \fBX10_OK\fP, \fBX10_NOT_OK\fP }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define bool   char"
.PP
.SS "#define EXTERN"
.PP
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned \fBx10_async_handler_t\fP"
.PP
.SS "typedef unsigned \fBx10_condition_t\fP"
.PP
.SS "typedef unsigned \fBx10_place_t\fP"
.PP
.SS "typedef \fBx10_proxy_t\fP \fBx10_remote_ref_t\fP"
.PP
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBx10_err_t\fP"
.PP
\fBEnumeration values: \fP
.in +1c
.TP
\fB\fIX10_OK \fP\fP
.TP
\fB\fIX10_NOT_OK \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
