.TH "__x10_async_descr_t" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__x10_async_descr_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__x10_async_type_t\fP \fB_async_type\fP"
.br
.ti -1c
.RI "\fBx10_async_closure_t\fP * \fBclosure\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__x10_normal_async_descr_t\fP \fB_normal_async_descr\fP"
.br
.ti -1c
.RI "   \fB__x10_global_async_descr_t\fP \fB_global_async_descr\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__x10_async_type_t\fP \fB__x10_async_descr_t::_async_type\fP"
.PP
.SS "\fB__x10_global_async_descr_t\fP \fB__x10_async_descr_t::_global_async_descr\fP"
.PP
.SS "\fB__x10_normal_async_descr_t\fP \fB__x10_async_descr_t::_normal_async_descr\fP"
.PP
.SS "\fBx10_async_closure_t\fP* \fB__x10_async_descr_t::closure\fP"
.PP
.SS "union { ... }  \fB__x10_async_descr_t::u\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
