#
# (c) Copyright IBM Corporation 2007
#
# $Id: Makefile,v 1.1.1.1 2007-04-25 09:57:46 srkodali Exp $
# This file is part of X10 Runtime System.
#

## Makefile for X10Lib Testing.

all:
	@echo "Done \"all\" in \"test\" subdir."

install:
	@echo "Done \"install\" in \"test\" subdir."

clean:
	@echo "Done \"clean\" in \"test\" subdir."

