.TH "x10_comm_handle_t" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x10_comm_handle_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <x10_types.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBrts_handle\fP"
.br
.ti -1c
.RI "void * \fBheader_buf\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBx10_comm_handle_t::header_buf\fP"
.PP
.SS "void* \fBx10_comm_handle_t::rts_handle\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
