#
# (c) Copyright IBM Corporation 2007
#
# $Id: Makefile,v 1.1 2007-04-27 12:54:54 srkodali Exp $
# This file is part of X10 Runtime System.
#

## Makefile for X10Lib Hostfiles.

all:
	@echo "Nothing to do in \"hostfiles\" subdir."

install:
	@echo "Nothing to do in \"hostfiles\" subdir."

clean:
	@echo "Nothing to do in \"hostfiles\" subdir."
