
//#line 18 "C:/eclipsews/v7/x10.compiler/src/x10/parser/x10.g"
//
// Licensed Material
// (C) Copyright IBM Corp, 2006
//

package x10.parser;

public interface X10Parsersym {
    public final static int
      TK_IntegerLiteral = 81,
      TK_LongLiteral = 82,
      TK_FloatingPointLiteral = 83,
      TK_DoubleLiteral = 84,
      TK_CharacterLiteral = 85,
      TK_StringLiteral = 86,
      TK_MINUS_MINUS = 90,
      TK_OR = 114,
      TK_MINUS = 95,
      TK_MINUS_EQUAL = 128,
      TK_NOT = 98,
      TK_NOT_EQUAL = 115,
      TK_REMAINDER = 119,
      TK_REMAINDER_EQUAL = 129,
      TK_AND = 116,
      TK_AND_AND = 120,
      TK_AND_EQUAL = 130,
      TK_LPAREN = 1,
      TK_RPAREN = 77,
      TK_MULTIPLY = 117,
      TK_MULTIPLY_EQUAL = 131,
      TK_COMMA = 89,
      TK_DOT = 94,
      TK_DIVIDE = 121,
      TK_DIVIDE_EQUAL = 132,
      TK_COLON = 101,
      TK_SEMICOLON = 79,
      TK_QUESTION = 126,
      TK_AT = 6,
      TK_LBRACKET = 76,
      TK_RBRACKET = 107,
      TK_XOR = 118,
      TK_XOR_EQUAL = 133,
      TK_LBRACE = 93,
      TK_OR_OR = 125,
      TK_OR_EQUAL = 134,
      TK_RBRACE = 102,
      TK_TWIDDLE = 99,
      TK_PLUS = 96,
      TK_PLUS_PLUS = 91,
      TK_PLUS_EQUAL = 135,
      TK_LESS = 110,
      TK_LEFT_SHIFT = 122,
      TK_LEFT_SHIFT_EQUAL = 136,
      TK_RIGHT_SHIFT = 123,
      TK_RIGHT_SHIFT_EQUAL = 137,
      TK_UNSIGNED_RIGHT_SHIFT = 124,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 138,
      TK_LESS_EQUAL = 111,
      TK_EQUAL = 97,
      TK_EQUAL_EQUAL = 103,
      TK_GREATER = 112,
      TK_GREATER_EQUAL = 113,
      TK_ELLIPSIS = 141,
      TK_RANGE = 140,
      TK_ARROW = 92,
      TK_DARROW = 127,
      TK_SUBTYPE = 108,
      TK_SUPERTYPE = 109,
      TK_abstract = 7,
      TK_as = 29,
      TK_assert = 47,
      TK_async = 48,
      TK_at = 49,
      TK_ateach = 39,
      TK_atomic = 20,
      TK_await = 50,
      TK_break = 51,
      TK_case = 27,
      TK_catch = 32,
      TK_class = 14,
      TK_clocked = 33,
      TK_const = 52,
      TK_continue = 53,
      TK_def = 16,
      TK_default = 28,
      TK_do = 40,
      TK_else = 41,
      TK_extends = 34,
      TK_extern = 21,
      TK_false = 54,
      TK_final = 8,
      TK_finally = 35,
      TK_finish = 55,
      TK_for = 42,
      TK_foreach = 43,
      TK_future = 104,
      TK_in = 105,
      TK_goto = 56,
      TK_has = 57,
      TK_here = 58,
      TK_if = 59,
      TK_implements = 44,
      TK_import = 36,
      TK_incomplete = 22,
      TK_instanceof = 30,
      TK_interface = 11,
      TK_local = 60,
      TK_native = 17,
      TK_new = 61,
      TK_next = 62,
      TK_nonblocking = 23,
      TK_now = 63,
      TK_null = 64,
      TK_or = 45,
      TK_operator = 100,
      TK_package = 37,
      TK_private = 2,
      TK_property = 18,
      TK_protected = 3,
      TK_public = 4,
      TK_return = 65,
      TK_rooted = 19,
      TK_safe = 12,
      TK_self = 66,
      TK_sequential = 24,
      TK_shared = 31,
      TK_static = 5,
      TK_strictfp = 9,
      TK_struct = 15,
      TK_super = 80,
      TK_switch = 67,
      TK_synchronized = 142,
      TK_this = 78,
      TK_throw = 68,
      TK_throws = 46,
      TK_transient = 25,
      TK_true = 69,
      TK_try = 70,
      TK_type = 10,
      TK_unsafe = 71,
      TK_val = 72,
      TK_value = 13,
      TK_var = 73,
      TK_volatile = 26,
      TK_when = 74,
      TK_while = 38,
      TK_EOF_TOKEN = 139,
      TK_IDENTIFIER = 75,
      TK_SlComment = 143,
      TK_MlComment = 144,
      TK_DocComment = 145,
      TK_UnsignedIntegerLiteral = 87,
      TK_UnsignedLongLiteral = 88,
      TK_ErrorId = 106,
      TK_TypeModifier = 146,
      TK_ERROR_TOKEN = 147;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "private",
                 "protected",
                 "public",
                 "static",
                 "AT",
                 "abstract",
                 "final",
                 "strictfp",
                 "type",
                 "interface",
                 "safe",
                 "value",
                 "class",
                 "struct",
                 "def",
                 "native",
                 "property",
                 "rooted",
                 "atomic",
                 "extern",
                 "incomplete",
                 "nonblocking",
                 "sequential",
                 "transient",
                 "volatile",
                 "case",
                 "default",
                 "as",
                 "instanceof",
                 "shared",
                 "catch",
                 "clocked",
                 "extends",
                 "finally",
                 "import",
                 "package",
                 "while",
                 "ateach",
                 "do",
                 "else",
                 "for",
                 "foreach",
                 "implements",
                 "or",
                 "throws",
                 "assert",
                 "async",
                 "at",
                 "await",
                 "break",
                 "const",
                 "continue",
                 "false",
                 "finish",
                 "goto",
                 "has",
                 "here",
                 "if",
                 "local",
                 "new",
                 "next",
                 "now",
                 "null",
                 "return",
                 "self",
                 "switch",
                 "throw",
                 "true",
                 "try",
                 "unsafe",
                 "val",
                 "var",
                 "when",
                 "IDENTIFIER",
                 "LBRACKET",
                 "RPAREN",
                 "this",
                 "SEMICOLON",
                 "super",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "UnsignedIntegerLiteral",
                 "UnsignedLongLiteral",
                 "COMMA",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "ARROW",
                 "LBRACE",
                 "DOT",
                 "MINUS",
                 "PLUS",
                 "EQUAL",
                 "NOT",
                 "TWIDDLE",
                 "operator",
                 "COLON",
                 "RBRACE",
                 "EQUAL_EQUAL",
                 "future",
                 "in",
                 "ErrorId",
                 "RBRACKET",
                 "SUBTYPE",
                 "SUPERTYPE",
                 "LESS",
                 "LESS_EQUAL",
                 "GREATER",
                 "GREATER_EQUAL",
                 "OR",
                 "NOT_EQUAL",
                 "AND",
                 "MULTIPLY",
                 "XOR",
                 "REMAINDER",
                 "AND_AND",
                 "DIVIDE",
                 "LEFT_SHIFT",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "OR_OR",
                 "QUESTION",
                 "DARROW",
                 "MINUS_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "EOF_TOKEN",
                 "RANGE",
                 "ELLIPSIS",
                 "synchronized",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "TypeModifier",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
