
//
// Licensed Material 
// (C) Copyright IBM Corp, 2006
//

package x10.parser;

public interface X10Parsersym {
    public final static int
      TK_abstract = 1,
      TK_assert = 2,
      TK_boolean = 3,
      TK_break = 4,
      TK_byte = 5,
      TK_case = 6,
      TK_catch = 7,
      TK_char = 8,
      TK_class = 9,
      TK_const = 10,
      TK_continue = 11,
      TK_default = 12,
      TK_do = 13,
      TK_double = 14,
      TK_enum = 15,
      TK_else = 16,
      TK_extends = 17,
      TK_false = 18,
      TK_final = 19,
      TK_finally = 20,
      TK_float = 21,
      TK_for = 22,
      TK_goto = 23,
      TK_if = 24,
      TK_implements = 25,
      TK_import = 26,
      TK_instanceof = 27,
      TK_int = 28,
      TK_interface = 29,
      TK_long = 30,
      TK_native = 31,
      TK_new = 32,
      TK_null = 33,
      TK_package = 34,
      TK_private = 35,
      TK_protected = 36,
      TK_public = 37,
      TK_return = 38,
      TK_short = 39,
      TK_static = 40,
      TK_strictfp = 41,
      TK_super = 42,
      TK_switch = 43,
      TK_synchronized = 44,
      TK_this = 45,
      TK_throw = 46,
      TK_throws = 47,
      TK_transient = 48,
      TK_true = 49,
      TK_try = 50,
      TK_void = 51,
      TK_volatile = 52,
      TK_while = 53,
      TK_activitylocal = 54,
      TK_async = 55,
      TK_ateach = 56,
      TK_atomic = 57,
      TK_await = 58,
      TK_boxed = 59,
      TK_clocked = 60,
      TK_current = 61,
      TK_extern = 62,
      TK_finish = 63,
      TK_foreach = 64,
      TK_fun = 65,
      TK_future = 66,
      TK_here = 67,
      TK_local = 68,
      TK_method = 69,
      TK_mutable = 70,
      TK_next = 71,
      TK_now = 72,
      TK_nullable = 73,
      TK_or = 74,
      TK_placelocal = 75,
      TK_reference = 76,
      TK_unsafe = 77,
      TK_value = 78,
      TK_when = 79,
      TK_EOF_TOKEN = 80,
      TK_IDENTIFIER = 81,
      TK_SlComment = 82,
      TK_MlComment = 83,
      TK_DocComment = 84,
      TK_IntegerLiteral = 85,
      TK_LongLiteral = 86,
      TK_FloatingPointLiteral = 87,
      TK_DoubleLiteral = 88,
      TK_CharacterLiteral = 89,
      TK_StringLiteral = 90,
      TK_PLUS_PLUS = 91,
      TK_MINUS_MINUS = 92,
      TK_EQUAL_EQUAL = 93,
      TK_LESS_EQUAL = 94,
      TK_GREATER_EQUAL = 95,
      TK_NOT_EQUAL = 96,
      TK_LEFT_SHIFT = 97,
      TK_RIGHT_SHIFT = 98,
      TK_UNSIGNED_RIGHT_SHIFT = 99,
      TK_PLUS_EQUAL = 100,
      TK_MINUS_EQUAL = 101,
      TK_MULTIPLY_EQUAL = 102,
      TK_DIVIDE_EQUAL = 103,
      TK_AND_EQUAL = 104,
      TK_OR_EQUAL = 105,
      TK_XOR_EQUAL = 106,
      TK_REMAINDER_EQUAL = 107,
      TK_LEFT_SHIFT_EQUAL = 108,
      TK_RIGHT_SHIFT_EQUAL = 109,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 110,
      TK_OR_OR = 111,
      TK_AND_AND = 112,
      TK_PLUS = 113,
      TK_MINUS = 114,
      TK_NOT = 115,
      TK_REMAINDER = 116,
      TK_XOR = 117,
      TK_AND = 118,
      TK_MULTIPLY = 119,
      TK_OR = 120,
      TK_TWIDDLE = 121,
      TK_DIVIDE = 122,
      TK_GREATER = 123,
      TK_LESS = 124,
      TK_LPAREN = 125,
      TK_RPAREN = 126,
      TK_LBRACE = 127,
      TK_RBRACE = 128,
      TK_LBRACKET = 129,
      TK_RBRACKET = 130,
      TK_SEMICOLON = 131,
      TK_QUESTION = 132,
      TK_AT = 133,
      TK_COLON = 134,
      TK_COMMA = 135,
      TK_DOT = 136,
      TK_EQUAL = 137,
      TK_ELLIPSIS = 138,
      TK_ARROW = 139;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "abstract",
                 "assert",
                 "boolean",
                 "break",
                 "byte",
                 "case",
                 "catch",
                 "char",
                 "class",
                 "const",
                 "continue",
                 "default",
                 "do",
                 "double",
                 "enum",
                 "else",
                 "extends",
                 "false",
                 "final",
                 "finally",
                 "float",
                 "for",
                 "goto",
                 "if",
                 "implements",
                 "import",
                 "instanceof",
                 "int",
                 "interface",
                 "long",
                 "native",
                 "new",
                 "null",
                 "package",
                 "private",
                 "protected",
                 "public",
                 "return",
                 "short",
                 "static",
                 "strictfp",
                 "super",
                 "switch",
                 "synchronized",
                 "this",
                 "throw",
                 "throws",
                 "transient",
                 "true",
                 "try",
                 "void",
                 "volatile",
                 "while",
                 "activitylocal",
                 "async",
                 "ateach",
                 "atomic",
                 "await",
                 "boxed",
                 "clocked",
                 "current",
                 "extern",
                 "finish",
                 "foreach",
                 "fun",
                 "future",
                 "here",
                 "local",
                 "method",
                 "mutable",
                 "next",
                 "now",
                 "nullable",
                 "or",
                 "placelocal",
                 "reference",
                 "unsafe",
                 "value",
                 "when",
                 "EOF_TOKEN",
                 "IDENTIFIER",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "PLUS_PLUS",
                 "MINUS_MINUS",
                 "EQUAL_EQUAL",
                 "LESS_EQUAL",
                 "GREATER_EQUAL",
                 "NOT_EQUAL",
                 "LEFT_SHIFT",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "PLUS_EQUAL",
                 "MINUS_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "AND_EQUAL",
                 "OR_EQUAL",
                 "XOR_EQUAL",
                 "REMAINDER_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "OR_OR",
                 "AND_AND",
                 "PLUS",
                 "MINUS",
                 "NOT",
                 "REMAINDER",
                 "XOR",
                 "AND",
                 "MULTIPLY",
                 "OR",
                 "TWIDDLE",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "LPAREN",
                 "RPAREN",
                 "LBRACE",
                 "RBRACE",
                 "LBRACKET",
                 "RBRACKET",
                 "SEMICOLON",
                 "QUESTION",
                 "AT",
                 "COLON",
                 "COMMA",
                 "DOT",
                 "EQUAL",
                 "ELLIPSIS",
                 "ARROW"
             };


    public final static boolean isValidForParser = false;
}
