
//
// This is the grammar specification from the Final Draft of the generic spec.
////
// This is the X10 grammar specification based on the Final Draft of the Java generic spec.
//
package x10.parser;

interface X10Parsersym {
    public final static int
      TK_IntegerLiteral = 67,
      TK_LongLiteral = 68,
      TK_FloatingPointLiteral = 69,
      TK_DoubleLiteral = 70,
      TK_CharacterLiteral = 71,
      TK_StringLiteral = 72,
      TK_MINUS_MINUS = 65,
      TK_OR = 85,
      TK_MINUS = 51,
      TK_MINUS_EQUAL = 117,
      TK_NOT = 73,
      TK_NOT_EQUAL = 89,
      TK_REMAINDER = 98,
      TK_REMAINDER_EQUAL = 118,
      TK_AND = 86,
      TK_AND_AND = 82,
      TK_AND_EQUAL = 119,
      TK_LPAREN = 1,
      TK_RPAREN = 48,
      TK_MULTIPLY = 96,
      TK_MULTIPLY_EQUAL = 120,
      TK_COMMA = 78,
      TK_DOT = 81,
      TK_DIVIDE = 99,
      TK_DIVIDE_EQUAL = 121,
      TK_COLON = 97,
      TK_SEMICOLON = 49,
      TK_QUESTION = 83,
      TK_AT = 45,
      TK_LBRACKET = 46,
      TK_RBRACKET = 105,
      TK_XOR = 87,
      TK_XOR_EQUAL = 122,
      TK_LBRACE = 64,
      TK_OR_OR = 84,
      TK_OR_EQUAL = 123,
      TK_RBRACE = 88,
      TK_TWIDDLE = 74,
      TK_PLUS = 50,
      TK_PLUS_PLUS = 66,
      TK_PLUS_EQUAL = 124,
      TK_LESS = 52,
      TK_LEFT_SHIFT = 94,
      TK_LEFT_SHIFT_EQUAL = 125,
      TK_LESS_EQUAL = 91,
      TK_EQUAL = 101,
      TK_EQUAL_EQUAL = 90,
      TK_GREATER = 79,
      TK_ELLIPSIS = 136,
      TK_RANGE = 47,
      TK_ARROW = 126,
      TK_abstract = 58,
      TK_assert = 106,
      TK_boolean = 11,
      TK_break = 107,
      TK_byte = 12,
      TK_case = 116,
      TK_catch = 131,
      TK_char = 13,
      TK_class = 92,
      TK_const = 138,
      TK_continue = 5,
      TK_default = 115,
      TK_do = 108,
      TK_double = 14,
      TK_enum = 95,
      TK_else = 127,
      TK_extends = 129,
      TK_false = 75,
      TK_final = 59,
      TK_finally = 132,
      TK_float = 15,
      TK_for = 109,
      TK_goto = 139,
      TK_if = 110,
      TK_implements = 137,
      TK_import = 133,
      TK_instanceof = 93,
      TK_int = 16,
      TK_interface = 80,
      TK_long = 17,
      TK_native = 128,
      TK_new = 61,
      TK_null = 76,
      TK_package = 134,
      TK_private = 54,
      TK_protected = 55,
      TK_public = 53,
      TK_return = 111,
      TK_short = 18,
      TK_static = 56,
      TK_strictfp = 60,
      TK_super = 62,
      TK_switch = 112,
      TK_synchronized = 100,
      TK_this = 63,
      TK_throw = 113,
      TK_throws = 135,
      TK_transient = 102,
      TK_true = 77,
      TK_try = 114,
      TK_void = 57,
      TK_volatile = 103,
      TK_while = 104,
      TK_async = 19,
      TK_ateach = 20,
      TK_atomic = 6,
      TK_await = 21,
      TK_clocked = 4,
      TK_current = 34,
      TK_distribution = 35,
      TK_drop = 7,
      TK_force = 36,
      TK_foreach = 22,
      TK_future = 23,
      TK_here = 37,
      TK_local = 38,
      TK_methodlocal = 39,
      TK_next = 8,
      TK_now = 24,
      TK_nullable = 25,
      TK_oneach = 26,
      TK_or = 27,
      TK_place = 28,
      TK_placelocal = 40,
      TK_pure = 29,
      TK_range = 41,
      TK_rank = 42,
      TK_reduce = 30,
      TK_reference = 3,
      TK_region = 43,
      TK_runsat = 9,
      TK_runson = 10,
      TK_scan = 31,
      TK_threadlocal = 44,
      TK_value = 2,
      TK_when = 32,
      TK_IDENTIFIER = 33,
      TK_GREATER_EQUAL = 140,
      TK_RIGHT_SHIFT = 141,
      TK_UNSIGNED_RIGHT_SHIFT = 142,
      TK_RIGHT_SHIFT_EQUAL = 143,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 144,
      TK_EOF_TOKEN = 130,
      TK_$error = 145;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "value",
                 "reference",
                 "clocked",
                 "continue",
                 "atomic",
                 "drop",
                 "next",
                 "runsat",
                 "runson",
                 "boolean",
                 "byte",
                 "char",
                 "double",
                 "float",
                 "int",
                 "long",
                 "short",
                 "async",
                 "ateach",
                 "await",
                 "foreach",
                 "future",
                 "now",
                 "nullable",
                 "oneach",
                 "or",
                 "place",
                 "pure",
                 "reduce",
                 "scan",
                 "when",
                 "IDENTIFIER",
                 "current",
                 "distribution",
                 "force",
                 "here",
                 "local",
                 "methodlocal",
                 "placelocal",
                 "range",
                 "rank",
                 "region",
                 "threadlocal",
                 "AT",
                 "LBRACKET",
                 "RANGE",
                 "RPAREN",
                 "SEMICOLON",
                 "PLUS",
                 "MINUS",
                 "LESS",
                 "public",
                 "private",
                 "protected",
                 "static",
                 "void",
                 "abstract",
                 "final",
                 "strictfp",
                 "new",
                 "super",
                 "this",
                 "LBRACE",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "NOT",
                 "TWIDDLE",
                 "false",
                 "null",
                 "true",
                 "COMMA",
                 "GREATER",
                 "interface",
                 "DOT",
                 "AND_AND",
                 "QUESTION",
                 "OR_OR",
                 "OR",
                 "AND",
                 "XOR",
                 "RBRACE",
                 "NOT_EQUAL",
                 "EQUAL_EQUAL",
                 "LESS_EQUAL",
                 "class",
                 "instanceof",
                 "LEFT_SHIFT",
                 "enum",
                 "MULTIPLY",
                 "COLON",
                 "REMAINDER",
                 "DIVIDE",
                 "synchronized",
                 "EQUAL",
                 "transient",
                 "volatile",
                 "while",
                 "RBRACKET",
                 "assert",
                 "break",
                 "do",
                 "for",
                 "if",
                 "return",
                 "switch",
                 "throw",
                 "try",
                 "default",
                 "case",
                 "MINUS_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "ARROW",
                 "else",
                 "native",
                 "extends",
                 "EOF_TOKEN",
                 "catch",
                 "finally",
                 "import",
                 "package",
                 "throws",
                 "ELLIPSIS",
                 "implements",
                 "const",
                 "goto",
                 "GREATER_EQUAL",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "$error"
             };

    public final static boolean isValidForParser = true;
}
