/*
 * Filename:x10_lang_Integer_x10stub.c
 * Generated: 6/9/08 3:52 PM */
/*Automatically generated -- DO NOT EDIT THIS FILE */
#include <sys/types.h>
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif

/* * * * * * * */
extern signed int   x10_lang_Integer_add(signed int x);
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1add(JNIEnv *env, jobject obj, jint x) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_add((signed int)x);

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1add) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1add
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1add")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_mul(signed int x);
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1mul(JNIEnv *env, jobject obj, jint x) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_mul((signed int)x);

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1mul) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1mul
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1mul")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_sub(signed int x);
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1sub(JNIEnv *env, jobject obj, jint x) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_sub((signed int)x);

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1sub) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1sub
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1sub")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_div(signed int x);
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1div(JNIEnv *env, jobject obj, jint x) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_div((signed int)x);

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1div) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1div
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1div")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_zero();
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1zero(JNIEnv *env, jobject obj) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_zero();

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1zero) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1zero
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1zero")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_unit();
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1unit(JNIEnv *env, jobject obj) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_unit();

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1unit) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1unit
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1unit")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_neginv();
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1neginv(JNIEnv *env, jobject obj) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_neginv();

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1neginv) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1neginv
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1neginv")));
#endif


/* * * * * * * */
extern signed int   x10_lang_Integer_mulinv();
JNIEXPORT jint JNICALL
Java_x10_lang_Integer_x10_1lang_1Integer_1mulinv(JNIEnv *env, jobject obj) {


signed int _x10ReTuRnVaL=(jint)  x10_lang_Integer_mulinv();

return _x10ReTuRnVaL;
}
#ifndef __WIN32__
extern JNIEXPORT __typeof(Java_x10_lang_Integer_x10_1lang_1Integer_1mulinv) JNICALL
_Java_x10_lang_Integer_x10_1lang_1Integer_1mulinv
__attribute((alias("Java_x10_lang_Integer_x10_1lang_1Integer_1mulinv")));
#endif


#ifdef __cplusplus
}
#endif
