.TH "AsyncQueue" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsyncQueue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <queue.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBx10_async_queue_el_t\fP \fB_head\fP"
.br
.ti -1c
.RI "\fBx10_async_queue_el_t\fP \fB_tail\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBx10_async_queue_el_t\fP \fBAsyncQueue::_head\fP"
.PP
.SS "\fBx10_async_queue_el_t\fP \fBAsyncQueue::_tail\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
