package lpg.lpgjavaruntime;

/**
 * Low-Level interface to act as recipient for error messages generated by a 
 * parser/compiler.
 */
public interface IMessageHandler {
    void handleMessage(int offset, int length, String message);
}