/*
 *
 * (C) Copyright IBM Corporation 2006
 *
 *  This file is part of X10 Test.
 *
 */
// Automatically generated by the command
// m4 ClockTest3a.m4 > ClockTest3a.x10
// Do not edit
import harness.x10Test;

/**
 * Clock test for barrier functions
 * @author kemal 3/2005
 */
public class ClockTest3a extends x10Test {

	var val: int = 0;
	const N: int = 32;

	public def run(): boolean = {
		val c: Clock = Clock.make();

		foreach (val (i): Point in 0..(N-1)) clocked(c) {
			async(here) clocked(c) finish async(here) { atomic val++; }
			next;
			if (val != N) {
				throw new Error();
			}
			next;
			async(here) clocked(c) finish async(here) { atomic val++; }
			next;
		}
		next; next; next;
		if (val != 2*N) {
			throw new Error();
		}
		return true;
	}

	public static def main(var args: Rail[String]): void = {
		new ClockTest3a().executeAsync();
	}
}
