/*******************************************************************************
 * Copyright (c) 2009 IBM Corporation.                                         *
 * All rights reserved. This program and the accompanying materials            *
 * are made available under the terms of the Eclipse Public License v1.0       *
 * which accompanies this distribution, and is available at                    *
 * http://www.eclipse.org/legal/epl-v10.html                                   *
 *******************************************************************************/
package org.eclipse.imp.x10dt.ui.launch.core.builder.operations;

import org.eclipse.core.resources.IContainer;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.imp.x10dt.ui.launch.core.platform_conf.IX10PlatformConfiguration;

/**
 * Provides operations useful for X10 builder regarding the files generated by X10 compiler.
 * 
 * @author egeay
 */
public interface IX10BuilderOp {
 
  /**
   * Archives the compiled generated files into a library.
   * 
   * @param platform The platform to consider.
   * @param monitor The monitor to consider for reporting progress or canceling the operation.
   * @throws CoreException Occurs if we could not transfer remotely some generated files.
   */
  public void archive(final IX10PlatformConfiguration platform, final IProgressMonitor monitor) throws CoreException;
  
  /**
   * Compiles the generated files on the target platform.
   * 
   * @param platform The platform to consider.
   * @param monitor The monitor to consider for reporting progress or canceling the operation.
   * @throws CoreException Occurs if we could not add some X10 markers to Problems View.
   * @return True if the compilation succeeded, false otherwise. In the latter, marker will be created and error will be 
   * logged.
   */
  public boolean compile(final IX10PlatformConfiguration platform, final IProgressMonitor monitor) throws CoreException;
  
  /**
   * Transfers the generated files to the workspace directory of the target platform.
   * 
   * @param binaryContainer The binary container containing the generated files.
   * @param monitor The monitor to consider for reporting progress or canceling the operation.
   * @throws CoreException Occurs if we could not add some X10 markers to Problems View.
   */
  public void transfer(final IContainer binaryContainer, final IProgressMonitor monitor) throws CoreException;

}
