.TH "tuple" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBplace\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBtuple::count\fP"
.PP
.SS "int \fBtuple::place\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
