.TH "refs.cc" 3 "20 May 2008" "Version 1.0" "X10LIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
refs.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include 'x10.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBx10_is_localref\fP (void *ref)"
.br
.RI "\fIcheck if the reference is local \fP"
.ti -1c
.RI "\fBx10_remote_ref_t\fP \fBx10_serialize_ref\fP (void *ref)"
.br
.RI "\fIremote reference serialize a reference (local or remote) \fP"
.ti -1c
.RI "void * \fBx10_deserialize_ref\fP (\fBx10_remote_ref_t\fP ref)"
.br
.RI "\fIdeserialize a remote reference \fP"
.ti -1c
.RI "int \fBx10_get_loc\fP (void *ref)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* x10_deserialize_ref (\fBx10_remote_ref_t\fP ref)"
.PP
deserialize a remote reference 
.PP
.SS "int x10_get_loc (void * ref)"
.PP
\\ brief get the location of a reference 
.SS "bool x10_is_localref (void * ref)"
.PP
check if the reference is local 
.PP
.SS "\fBx10_remote_ref_t\fP x10_serialize_ref (void * ref)"
.PP
remote reference serialize a reference (local or remote) 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for X10LIB from the source code.
