// Automatically generated by /u/x10/x10/bin/makeTestCompiler 
// Do not edit
package polyglot.ext.x10.tests;

import junit.framework.TestSuite;

/*
 * Created by vj on Jan 11, 2005
 *
 * 
 */

/**
 * @author vj Jan 11, 2005
 * 
 */
public class TestCompiler extends TestX10_Compiler {

/**
 * @param name
 */
public TestCompiler(String name) {
	super(name);
}

    public void test_Applications_GameOfLife() {
        run("./GameOfLife.x10","GameOfLife","./Applications");
    }

    public void test_Applications_JGFCryptBenchSizeA() {
        run("./JGFCryptBenchSizeA.x10","JGFCryptBenchSizeA","./Applications");
    }

    public void test_Applications_JGFLUFactBenchSizeA() {
        run("./JGFLUFactBenchSizeA.x10","JGFLUFactBenchSizeA","./Applications");
    }

    public void test_Applications_JGFMolDynBenchSizeA() {
        run("./JGFMolDynBenchSizeA.x10","JGFMolDynBenchSizeA","./Applications");
    }

    public void test_Applications_JGFMonteCarloBenchSizeA() {
        run("./JGFMonteCarloBenchSizeA.x10","JGFMonteCarloBenchSizeA","./Applications");
    }

    public void test_Applications_JGFRayTracerBenchSizeA() {
        run("./JGFRayTracerBenchSizeA.x10","JGFRayTracerBenchSizeA","./Applications");
    }

    public void test_Applications_JGFSORBenchSizeA() {
        run("./JGFSORBenchSizeA.x10","JGFSORBenchSizeA","./Applications");
    }

    public void test_Applications_JGFSeriesBenchSizeA() {
        run("./JGFSeriesBenchSizeA.x10","JGFSeriesBenchSizeA","./Applications");
    }

    public void test_Applications_JGFSparseMatmultBenchSizeA() {
        run("./JGFSparseMatmultBenchSizeA.x10","JGFSparseMatmultBenchSizeA","./Applications");
    }

    public void test_Applications_Jacobi() {
        run("./Jacobi.x10","Jacobi","./Applications");
    }

    public void test_Applications_JacobiSmall() {
        run("./JacobiSmall.x10","JacobiSmall","./Applications");
    }

    public void test_Applications_Jacobi_skewed() {
        run("./Jacobi_skewed.x10","Jacobi_skewed","./Applications");
    }

    public void test_Applications_MpiExample() {
        run("./MpiExample.x10","MpiExample","./Applications");
    }

    public void test_Applications_MpiExample2() {
        run("./MpiExample2.x10","MpiExample2","./Applications");
    }

    public void test_Applications_QueensList() {
        run("./QueensList.x10","QueensList","./Applications");
    }

    public void test_Applications_QueensList3() {
        run("./QueensList3.x10","QueensList3","./Applications");
    }

    public void test_Applications_RandomAccess() {
        run("./RandomAccess.x10","RandomAccess","./Applications");
    }

    public void test_Applications_RandomAccess_int() {
        run("./RandomAccess_int.x10","RandomAccess_int","./Applications");
    }

    public void test_Applications_RandomAccess_long() {
        run("./RandomAccess_long.x10","RandomAccess_long","./Applications");
    }

    public void test_Applications_RandomAccess_skewed() {
        run("./RandomAccess_skewed.x10","RandomAccess_skewed","./Applications");
    }

    public void test_Constructs_Array_Array1() {
        run("./Array1.x10","Array1","./Constructs/Array");
    }

    public void test_Constructs_Array_Array1Exploded() {
        run("./Array1Exploded.x10","Array1Exploded","./Constructs/Array");
    }

    public void test_Constructs_Array_Array1Long() {
        run("./Array1Long.x10","Array1Long","./Constructs/Array");
    }

    public void test_Constructs_Array_Array1s() {
        run("./Array1s.x10","Array1s","./Constructs/Array");
    }

    public void test_Constructs_Array_Array2v() {
        run("./Array2v.x10","Array2v","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3() {
        run("./Array3.x10","Array3","./Constructs/Array");
    }

    public void test_Constructs_Array_Array31() {
        run("./Array31.x10","Array31","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Boolean() {
        run("./Array3Boolean.x10","Array3Boolean","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Byte() {
        run("./Array3Byte.x10","Array3Byte","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Char() {
        run("./Array3Char.x10","Array3Char","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Double() {
        run("./Array3Double.x10","Array3Double","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Float() {
        run("./Array3Float.x10","Array3Float","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Long() {
        run("./Array3Long.x10","Array3Long","./Constructs/Array");
    }

    public void test_Constructs_Array_Array3Short() {
        run("./Array3Short.x10","Array3Short","./Constructs/Array");
    }

    public void test_Constructs_Array_Array4() {
        run("./Array4.x10","Array4","./Constructs/Array");
    }

    public void test_Constructs_Array_Array5() {
        run("./Array5.x10","Array5","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayAlgebra() {
        run("./ArrayAlgebra.x10","ArrayAlgebra","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayBounds1D() {
        run("./ArrayBounds1D.x10","ArrayBounds1D","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayBounds2D() {
        run("./ArrayBounds2D.x10","ArrayBounds2D","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayBounds3D() {
        run("./ArrayBounds3D.x10","ArrayBounds3D","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayCopy1() {
        run("./ArrayCopy1.x10","ArrayCopy1","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayCopy2() {
        run("./ArrayCopy2.x10","ArrayCopy2","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayCopy3() {
        run("./ArrayCopy3.x10","ArrayCopy3","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayDecl() {
        run("./ArrayDecl.x10","ArrayDecl","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayInitializer() {
        run("./ArrayInitializer.x10","ArrayInitializer","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayInitializerShorthand() {
        run("./ArrayInitializerShorthand.x10","ArrayInitializerShorthand","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayOpAssign() {
        run("./ArrayOpAssign.x10","ArrayOpAssign","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayOpAssign2() {
        run("./ArrayOpAssign2.x10","ArrayOpAssign2","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayOverRegion() {
        run("./ArrayOverRegion.x10","ArrayOverRegion","./Constructs/Array");
    }

    public void test_Constructs_Array_ArrayTypeCheck_MustFailCompile() {
        run("./ArrayTypeCheck_MustFailCompile.x10","ArrayTypeCheck_MustFailCompile","./Constructs/Array");
    }

    public void test_Constructs_Array_IntArrayInitializerShorthand() {
        run("./IntArrayInitializerShorthand.x10","IntArrayInitializerShorthand","./Constructs/Array");
    }

    public void test_Constructs_Array_IntArrayMaxAbs() {
        run("./IntArrayMaxAbs.x10","IntArrayMaxAbs","./Constructs/Array");
    }

    public void test_Constructs_Array_IntValueArrayInitializerShorthand() {
        run("./IntValueArrayInitializerShorthand.x10","IntValueArrayInitializerShorthand","./Constructs/Array");
    }

    public void test_Constructs_Array_MiscTest1() {
        run("./MiscTest1.x10","MiscTest1","./Constructs/Array");
    }

    public void test_Constructs_Array_UserDefinedArray() {
        run("./UserDefinedArray.x10","UserDefinedArray","./Constructs/Array");
    }

    public void test_Constructs_Async_AsyncFieldAccess() {
        run("./AsyncFieldAccess.x10","AsyncFieldAccess","./Constructs/Async");
    }

    public void test_Constructs_Async_AsyncTest() {
        run("./AsyncTest.x10","AsyncTest","./Constructs/Async");
    }

    public void test_Constructs_Async_AsyncTest1() {
        run("./AsyncTest1.x10","AsyncTest1","./Constructs/Async");
    }

    public void test_Constructs_Async_AsyncTest2() {
        run("./AsyncTest2.x10","AsyncTest2","./Constructs/Async");
    }

    public void test_Constructs_Async_AsyncTest3_MustFailCompile() {
        run("./AsyncTest3_MustFailCompile.x10","AsyncTest3_MustFailCompile","./Constructs/Async");
    }

    public void test_Constructs_Async_AsyncTest4_MustFailCompile() {
        run("./AsyncTest4_MustFailCompile.x10","AsyncTest4_MustFailCompile","./Constructs/Async");
    }

    public void test_Constructs_AtEach_AtEach() {
        run("./AtEach.x10","AtEach","./Constructs/AtEach");
    }

    public void test_Constructs_AtEach_AtEach2() {
        run("./AtEach2.x10","AtEach2","./Constructs/AtEach");
    }

    public void test_Constructs_AtEach_AtEachLoopOnArray() {
        run("./AtEachLoopOnArray.x10","AtEachLoopOnArray","./Constructs/AtEach");
    }

    public void test_Constructs_Atomic_Atomic1() {
        run("./Atomic1.x10","Atomic1","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_Atomic2() {
        run("./Atomic2.x10","Atomic2","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_AtomicMethodTest() {
        run("./AtomicMethodTest.x10","AtomicMethodTest","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_AtomicReturn() {
        run("./AtomicReturn.x10","AtomicReturn","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_AtomicTest() {
        run("./AtomicTest.x10","AtomicTest","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_AwaitTest() {
        run("./AwaitTest.x10","AwaitTest","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_AwaitTest2() {
        run("./AwaitTest2.x10","AwaitTest2","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_ConditionalAtomicQueue() {
        run("./ConditionalAtomicQueue.x10","ConditionalAtomicQueue","./Constructs/Atomic");
    }

    public void test_Constructs_Atomic_ConditionalAtomicTest() {
        run("./ConditionalAtomicTest.x10","ConditionalAtomicTest","./Constructs/Atomic");
    }

    public void test_Constructs_Boxing_Boxing0() {
        run("./Boxing0.x10","Boxing0","./Constructs/Boxing");
    }

    public void test_Constructs_Boxing_Boxing1() {
        run("./Boxing1.x10","Boxing1","./Constructs/Boxing");
    }

    public void test_Constructs_Boxing_Boxing2() {
        run("./Boxing2.x10","Boxing2","./Constructs/Boxing");
    }

    public void test_Constructs_Clock_ClockTest() {
        run("./ClockTest.x10","ClockTest","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest1() {
        run("./ClockTest1.x10","ClockTest1","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest10() {
        run("./ClockTest10.x10","ClockTest10","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest10a() {
        run("./ClockTest10a.x10","ClockTest10a","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest11_MustFailCompile() {
        run("./ClockTest11_MustFailCompile.x10","ClockTest11_MustFailCompile","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest12() {
        run("./ClockTest12.x10","ClockTest12","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest13() {
        run("./ClockTest13.x10","ClockTest13","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest14() {
        run("./ClockTest14.x10","ClockTest14","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest15() {
        run("./ClockTest15.x10","ClockTest15","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest15WithResume() {
        run("./ClockTest15WithResume.x10","ClockTest15WithResume","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest2() {
        run("./ClockTest2.x10","ClockTest2","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest3() {
        run("./ClockTest3.x10","ClockTest3","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest3a() {
        run("./ClockTest3a.x10","ClockTest3a","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest3b() {
        run("./ClockTest3b.x10","ClockTest3b","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest4() {
        run("./ClockTest4.x10","ClockTest4","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest5() {
        run("./ClockTest5.x10","ClockTest5","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest6() {
        run("./ClockTest6.x10","ClockTest6","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest7_MustFailRun() {
        run("./ClockTest7_MustFailRun.x10","ClockTest7_MustFailRun","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest8_MustFailCompile() {
        run("./ClockTest8_MustFailCompile.x10","ClockTest8_MustFailCompile","./Constructs/Clock");
    }

    public void test_Constructs_Clock_ClockTest9() {
        run("./ClockTest9.x10","ClockTest9","./Constructs/Clock");
    }

    public void test_Constructs_Distribution_ArrayToDist() {
        run("./ArrayToDist.x10","ArrayToDist","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_BlockCyclicDist() {
        run("./BlockCyclicDist.x10","BlockCyclicDist","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_BlockDist() {
        run("./BlockDist.x10","BlockDist","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_CyclicDist() {
        run("./CyclicDist.x10","CyclicDist","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistAlgebra() {
        run("./DistAlgebra.x10","DistAlgebra","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistAlgebra2() {
        run("./DistAlgebra2.x10","DistAlgebra2","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistAlgebra2_MustFailRun() {
        run("./DistAlgebra2_MustFailRun.x10","DistAlgebra2_MustFailRun","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistBounds1D() {
        run("./DistBounds1D.x10","DistBounds1D","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistBounds2D() {
        run("./DistBounds2D.x10","DistBounds2D","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistBounds3D() {
        run("./DistBounds3D.x10","DistBounds3D","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistributionTest() {
        run("./DistributionTest.x10","DistributionTest","./Constructs/Distribution");
    }

    public void test_Constructs_Distribution_DistributionTest1() {
        run("./DistributionTest1.x10","DistributionTest1","./Constructs/Distribution");
    }

    public void test_Constructs_Exceptions_Exceptions() {
        run("./Exceptions.x10","Exceptions","./Constructs/Exceptions");
    }

    public void test_Constructs_Exceptions_Exceptions2() {
        run("./Exceptions2.x10","Exceptions2","./Constructs/Exceptions");
    }

    public void test_Constructs_Extern_BasicExternTest1() {
        run("./BasicExternTest1.x10","BasicExternTest1","./Constructs/Extern");
    }

    public void test_Constructs_Extern_IntArrayExternUnsafe() {
        run("./IntArrayExternUnsafe.x10","IntArrayExternUnsafe","./Constructs/Extern");
    }

    public void test_Constructs_Extern_JacobiExtern() {
        run("./JacobiExtern.x10","JacobiExtern","./Constructs/Extern");
    }

    public void test_Constructs_Extern_RandomAccess_longExtern() {
        run("./RandomAccess_longExtern.x10","RandomAccess_longExtern","./Constructs/Extern");
    }

    public void test_Constructs_Final_ImplicitFinal() {
        run("./ImplicitFinal.x10","ImplicitFinal","./Constructs/Final");
    }

    public void test_Constructs_Finish_FinishTest1() {
        run("./FinishTest1.x10","FinishTest1","./Constructs/Finish");
    }

    public void test_Constructs_For_ForLoop() {
        run("./ForLoop.x10","ForLoop","./Constructs/For");
    }

    public void test_Constructs_For_ForLoop2() {
        run("./ForLoop2.x10","ForLoop2","./Constructs/For");
    }

    public void test_Constructs_For_ForLoop3() {
        run("./ForLoop3.x10","ForLoop3","./Constructs/For");
    }

    public void test_Constructs_For_ForLoop4() {
        run("./ForLoop4.x10","ForLoop4","./Constructs/For");
    }

    public void test_Constructs_For_ForLoopOnArray() {
        run("./ForLoopOnArray.x10","ForLoopOnArray","./Constructs/For");
    }

    public void test_Constructs_ForEach_Foreach2() {
        run("./Foreach2.x10","Foreach2","./Constructs/ForEach");
    }

    public void test_Constructs_Future_Future0() {
        run("./Future0.x10","Future0","./Constructs/Future");
    }

    public void test_Constructs_Future_Future1() {
        run("./Future1.x10","Future1","./Constructs/Future");
    }

    public void test_Constructs_Future_Future1Boxed() {
        run("./Future1Boxed.x10","Future1Boxed","./Constructs/Future");
    }

    public void test_Constructs_Future_Future2Boxed() {
        run("./Future2Boxed.x10","Future2Boxed","./Constructs/Future");
    }

    public void test_Constructs_Future_Future3() {
        run("./Future3.x10","Future3","./Constructs/Future");
    }

    public void test_Constructs_Future_Future3Boxed() {
        run("./Future3Boxed.x10","Future3Boxed","./Constructs/Future");
    }

    public void test_Constructs_Future_Future4() {
        run("./Future4.x10","Future4","./Constructs/Future");
    }

    public void test_Constructs_Future_Future4Boxed() {
        run("./Future4Boxed.x10","Future4Boxed","./Constructs/Future");
    }

    public void test_Constructs_Future_FutureNullable0() {
        run("./FutureNullable0.x10","FutureNullable0","./Constructs/Future");
    }

    public void test_Constructs_Future_FutureNullable1Boxed() {
        run("./FutureNullable1Boxed.x10","FutureNullable1Boxed","./Constructs/Future");
    }

    public void test_Constructs_Future_FutureTest2() {
        run("./FutureTest2.x10","FutureTest2","./Constructs/Future");
    }

    public void test_Constructs_Future_FutureTest3() {
        run("./FutureTest3.x10","FutureTest3","./Constructs/Future");
    }

    public void test_Constructs_Future_FutureTest4_MustFailCompile() {
        run("./FutureTest4_MustFailCompile.x10","FutureTest4_MustFailCompile","./Constructs/Future");
    }

    public void test_Constructs_Import_ClasspathTest() {
        run("./ClasspathTest.x10","ClasspathTest","./Constructs/Import");
    }

    public void test_Constructs_Import_ImportTest() {
        run("./ImportTest.x10","ImportTest","./Constructs/Import");
    }

    public void test_Constructs_Import_ImportTestPackage1_SubPackage_T3() {
        run("./ImportTestPackage1/SubPackage/T3.x10","ImportTestPackage1.SubPackage.T3","./Constructs/Import");
    }

    public void test_Constructs_Init_InitNonNullable_MustFailCompile() {
        run("./InitNonNullable_MustFailCompile.x10","InitNonNullable_MustFailCompile","./Constructs/Init");
    }

    public void test_Constructs_Nullable_Nullable0Ref() {
        run("./Nullable0Ref.x10","Nullable0Ref","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_Nullable1() {
        run("./Nullable1.x10","Nullable1","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_Nullable2() {
        run("./Nullable2.x10","Nullable2","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_Nullable5() {
        run("./Nullable5.x10","Nullable5","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableArray() {
        run("./NullableArray.x10","NullableArray","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableArray2() {
        run("./NullableArray2.x10","NullableArray2","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableArray3_MustFailCompile() {
        run("./NullableArray3_MustFailCompile.x10","NullableArray3_MustFailCompile","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableFuture0() {
        run("./NullableFuture0.x10","NullableFuture0","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableFuture1() {
        run("./NullableFuture1.x10","NullableFuture1","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableFuture2() {
        run("./NullableFuture2.x10","NullableFuture2","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableObject() {
        run("./NullableObject.x10","NullableObject","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableObject2() {
        run("./NullableObject2.x10","NullableObject2","./Constructs/Nullable");
    }

    public void test_Constructs_Nullable_NullableObject3() {
        run("./NullableObject3.x10","NullableObject3","./Constructs/Nullable");
    }

    public void test_Constructs_Region_RegionAlgebra() {
        run("./RegionAlgebra.x10","RegionAlgebra","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionConvexHull() {
        run("./RegionConvexHull.x10","RegionConvexHull","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionTest01() {
        run("./RegionTest01.x10","RegionTest01","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionTest1() {
        run("./RegionTest1.x10","RegionTest1","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionTest2() {
        run("./RegionTest2.x10","RegionTest2","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionTestIterator() {
        run("./RegionTestIterator.x10","RegionTestIterator","./Constructs/Region");
    }

    public void test_Constructs_Region_RegionTriangular() {
        run("./RegionTriangular.x10","RegionTriangular","./Constructs/Region");
    }

    public void test_Constructs_StorageClass_StorageClassesTest() {
        run("./StorageClassesTest.x10","StorageClassesTest","./Constructs/StorageClass");
    }

    public void test_Constructs_Unsafe_Unsafe() {
        run("./Unsafe.x10","Unsafe","./Constructs/Unsafe");
    }

    public void test_Constructs_Value_ValueClass() {
        run("./ValueClass.x10","ValueClass","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClass2_MustFailCompile() {
        run("./ValueClass2_MustFailCompile.x10","ValueClass2_MustFailCompile","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClass3_MustFailCompile() {
        run("./ValueClass3_MustFailCompile.x10","ValueClass3_MustFailCompile","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClass4() {
        run("./ValueClass4.x10","ValueClass4","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClass5_MustFailCompile() {
        run("./ValueClass5_MustFailCompile.x10","ValueClass5_MustFailCompile","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClass6() {
        run("./ValueClass6.x10","ValueClass6","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueClassUserDefinedEquals() {
        run("./ValueClassUserDefinedEquals.x10","ValueClassUserDefinedEquals","./Constructs/Value");
    }

    public void test_Constructs_Value_ValueEquality() {
        run("./ValueEquality.x10","ValueEquality","./Constructs/Value");
    }

    public void test_Misc_CommentTest() {
        run("./CommentTest.x10","CommentTest","./Misc");
    }

    public void test_Misc_ExpressionParentheses() {
        run("./ExpressionParentheses.x10","ExpressionParentheses","./Misc");
    }

    public void test_Misc_FinalInitializationTest() {
        run("./FinalInitializationTest.x10","FinalInitializationTest","./Misc");
    }

    public void test_Misc_LiteralTest() {
        run("./LiteralTest.x10","LiteralTest","./Misc");
    }

    public void test_Misc_NonX10Constructs_MustFailCompile() {
        run("./NonX10Constructs_MustFailCompile.x10","NonX10Constructs_MustFailCompile","./Misc");
    }

    public void test_Misc_NopTest() {
        run("./NopTest.x10","NopTest","./Misc");
    }

    public void test_Misc_RemoteAccessCheck() {
        run("./RemoteAccessCheck.x10","RemoteAccessCheck","./Misc");
    }

    public void test_Misc_SimpleDataRace_MustFailRun() {
        run("./SimpleDataRace_MustFailRun.x10","SimpleDataRace_MustFailRun","./Misc");
    }

    public void test_Misc_StringTest() {
        run("./StringTest.x10","StringTest","./Misc");
    }

    public void test_Misc_Unreachable() {
        run("./Unreachable.x10","Unreachable","./Misc");
    }

    public void test_Misc_VariableScope() {
        run("./VariableScope.x10","VariableScope","./Misc");
    }

    public void test_Timings_ArrayIndexing() {
        run("./ArrayIndexing.x10","ArrayIndexing","./Timings");
    }

    public void test_Timings_Initialization() {
        run("./Initialization.x10","Initialization","./Timings");
    }

    public static void main(String args[]) {
        TestX10_Compiler.Main(TestCompiler.class);
    }
    public static TestSuite suite() {
        return TestX10_Compiler.suite(TestCompiler.class);
    }
}
