
//#line 18 "x10.g"
//
// Licensed Material
// (C) Copyright IBM Corp, 2006
//

//
// This is the grammar specification from the Final Draft of the generic spec.
// It has been modified by Philippe Charles and Vijay Saraswat for use with 
// X10. 
// (1) Removed TypeParameters from class/interface/method declarations
// (2) Removed TypeParameters from types.
// (3) Removed Annotations -- cause conflicts with @ used in places.
// (4) Removed EnumDeclarations.
// 12/28/2004

package x10.parser;

public interface X10Parsersym {
    public final static int
      TK_IntegerLiteral = 51,
      TK_LongLiteral = 52,
      TK_FloatingPointLiteral = 53,
      TK_DoubleLiteral = 54,
      TK_CharacterLiteral = 55,
      TK_StringLiteral = 56,
      TK_MINUS_MINUS = 64,
      TK_OR = 123,
      TK_MINUS = 71,
      TK_MINUS_EQUAL = 112,
      TK_NOT = 73,
      TK_NOT_EQUAL = 106,
      TK_REMAINDER = 102,
      TK_REMAINDER_EQUAL = 113,
      TK_AND = 124,
      TK_AND_AND = 107,
      TK_AND_EQUAL = 114,
      TK_LPAREN = 1,
      TK_RPAREN = 44,
      TK_MULTIPLY = 98,
      TK_MULTIPLY_EQUAL = 115,
      TK_COMMA = 75,
      TK_DOT = 66,
      TK_DIVIDE = 103,
      TK_DIVIDE_EQUAL = 116,
      TK_COLON = 74,
      TK_SEMICOLON = 46,
      TK_QUESTION = 125,
      TK_AT = 5,
      TK_LBRACKET = 43,
      TK_RBRACKET = 80,
      TK_XOR = 108,
      TK_XOR_EQUAL = 117,
      TK_LBRACE = 69,
      TK_OR_OR = 126,
      TK_OR_EQUAL = 118,
      TK_RBRACE = 97,
      TK_TWIDDLE = 79,
      TK_PLUS = 72,
      TK_PLUS_PLUS = 65,
      TK_PLUS_EQUAL = 119,
      TK_LESS = 95,
      TK_LEFT_SHIFT = 105,
      TK_LEFT_SHIFT_EQUAL = 120,
      TK_LESS_EQUAL = 104,
      TK_EQUAL = 94,
      TK_EQUAL_EQUAL = 109,
      TK_GREATER = 77,
      TK_ELLIPSIS = 135,
      TK_ARROW = 47,
      TK_abstract = 68,
      TK_assert = 83,
      TK_boolean = 14,
      TK_break = 84,
      TK_byte = 15,
      TK_case = 110,
      TK_catch = 129,
      TK_char = 16,
      TK_class = 76,
      TK_const = 99,
      TK_continue = 85,
      TK_default = 111,
      TK_do = 86,
      TK_double = 17,
      TK_enum = 138,
      TK_else = 121,
      TK_extends = 130,
      TK_false = 57,
      TK_final = 67,
      TK_finally = 131,
      TK_float = 18,
      TK_for = 87,
      TK_goto = 139,
      TK_if = 88,
      TK_implements = 127,
      TK_import = 132,
      TK_instanceof = 122,
      TK_int = 19,
      TK_interface = 78,
      TK_long = 20,
      TK_native = 133,
      TK_new = 58,
      TK_null = 59,
      TK_package = 136,
      TK_private = 61,
      TK_protected = 62,
      TK_property = 89,
      TK_public = 50,
      TK_return = 90,
      TK_short = 21,
      TK_static = 63,
      TK_strictfp = 70,
      TK_super = 49,
      TK_switch = 91,
      TK_synchronized = 81,
      TK_this = 45,
      TK_throw = 92,
      TK_throws = 134,
      TK_transient = 100,
      TK_true = 60,
      TK_try = 93,
      TK_void = 48,
      TK_volatile = 101,
      TK_while = 82,
      TK_activitylocal = 22,
      TK_any = 137,
      TK_async = 23,
      TK_ateach = 24,
      TK_atomic = 8,
      TK_await = 25,
      TK_boxed = 26,
      TK_clocked = 7,
      TK_compilertest = 27,
      TK_current = 28,
      TK_extern = 9,
      TK_finish = 29,
      TK_foreach = 30,
      TK_fun = 31,
      TK_future = 32,
      TK_here = 33,
      TK_local = 10,
      TK_method = 34,
      TK_mutable = 11,
      TK_next = 35,
      TK_nonblocking = 12,
      TK_now = 36,
      TK_nullable = 37,
      TK_or = 6,
      TK_placelocal = 38,
      TK_reference = 39,
      TK_safe = 3,
      TK_self = 40,
      TK_sequential = 13,
      TK_unsafe = 4,
      TK_value = 2,
      TK_when = 41,
      TK_EOF_TOKEN = 128,
      TK_IDENTIFIER = 42,
      TK_SlComment = 140,
      TK_MlComment = 141,
      TK_DocComment = 142,
      TK_GREATER_EQUAL = 143,
      TK_RIGHT_SHIFT = 144,
      TK_UNSIGNED_RIGHT_SHIFT = 145,
      TK_RIGHT_SHIFT_EQUAL = 146,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 147,
      TK_ErrorId = 96,
      TK_ERROR_TOKEN = 148;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "value",
                 "safe",
                 "unsafe",
                 "AT",
                 "or",
                 "clocked",
                 "atomic",
                 "extern",
                 "local",
                 "mutable",
                 "nonblocking",
                 "sequential",
                 "boolean",
                 "byte",
                 "char",
                 "double",
                 "float",
                 "int",
                 "long",
                 "short",
                 "activitylocal",
                 "async",
                 "ateach",
                 "await",
                 "boxed",
                 "compilertest",
                 "current",
                 "finish",
                 "foreach",
                 "fun",
                 "future",
                 "here",
                 "method",
                 "next",
                 "now",
                 "nullable",
                 "placelocal",
                 "reference",
                 "self",
                 "when",
                 "IDENTIFIER",
                 "LBRACKET",
                 "RPAREN",
                 "this",
                 "SEMICOLON",
                 "ARROW",
                 "void",
                 "super",
                 "public",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "false",
                 "new",
                 "null",
                 "true",
                 "private",
                 "protected",
                 "static",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "DOT",
                 "final",
                 "abstract",
                 "LBRACE",
                 "strictfp",
                 "MINUS",
                 "PLUS",
                 "NOT",
                 "COLON",
                 "COMMA",
                 "class",
                 "GREATER",
                 "interface",
                 "TWIDDLE",
                 "RBRACKET",
                 "synchronized",
                 "while",
                 "assert",
                 "break",
                 "continue",
                 "do",
                 "for",
                 "if",
                 "property",
                 "return",
                 "switch",
                 "throw",
                 "try",
                 "EQUAL",
                 "LESS",
                 "ErrorId",
                 "RBRACE",
                 "MULTIPLY",
                 "const",
                 "transient",
                 "volatile",
                 "REMAINDER",
                 "DIVIDE",
                 "LESS_EQUAL",
                 "LEFT_SHIFT",
                 "NOT_EQUAL",
                 "AND_AND",
                 "XOR",
                 "EQUAL_EQUAL",
                 "case",
                 "default",
                 "MINUS_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "else",
                 "instanceof",
                 "OR",
                 "AND",
                 "QUESTION",
                 "OR_OR",
                 "implements",
                 "EOF_TOKEN",
                 "catch",
                 "extends",
                 "finally",
                 "import",
                 "native",
                 "throws",
                 "ELLIPSIS",
                 "package",
                 "any",
                 "enum",
                 "goto",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "GREATER_EQUAL",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
