// Automatically generated by /home/kemal/x10/bin/makeTestCompiler 
// Do not edit
package polyglot.ext.x10.tests;

import junit.framework.TestSuite;

/*
 * Created by vj on Jan 11, 2005
 *
 * 
 */

/**
 * @author vj Jan 11, 2005
 * 
 */
public class TestCompiler extends TestX10_Compiler {

/**
 * @param name
 */
public TestCompiler(String name) {
	super(name);
}

    public void test_Array1() {
        run("./Array1.x10","Array1");
    }

    public void test_Array1Exploded() {
        run("./Array1Exploded.x10","Array1Exploded");
    }

    public void test_Array1Long() {
        run("./Array1Long.x10","Array1Long");
    }

    public void test_Array1s() {
        run("./Array1s.x10","Array1s");
    }

    public void test_Array2v() {
        run("./Array2v.x10","Array2v");
    }

    public void test_Array3() {
        run("./Array3.x10","Array3");
    }

    public void test_Array31() {
        run("./Array31.x10","Array31");
    }

    public void test_Array3Long() {
        run("./Array3Long.x10","Array3Long");
    }

    public void test_Array4() {
        run("./Array4.x10","Array4");
    }

    public void test_Array5() {
        run("./Array5.x10","Array5");
    }

    public void test_ArrayBounds1D() {
        run("./ArrayBounds1D.x10","ArrayBounds1D");
    }

    public void test_ArrayBounds2D() {
        run("./ArrayBounds2D.x10","ArrayBounds2D");
    }

    public void test_ArrayBounds3D() {
        run("./ArrayBounds3D.x10","ArrayBounds3D");
    }

    public void test_ArrayCopy1() {
        run("./ArrayCopy1.x10","ArrayCopy1");
    }

    public void test_ArrayCopy2() {
        run("./ArrayCopy2.x10","ArrayCopy2");
    }

    public void test_ArrayCopy2v() {
        run("./ArrayCopy2v.x10","ArrayCopy2v");
    }

    public void test_ArrayCopy3() {
        run("./ArrayCopy3.x10","ArrayCopy3");
    }

    public void test_ArrayInitializer() {
        run("./ArrayInitializer.x10","ArrayInitializer");
    }

    public void test_ArrayInitializerShorthand() {
        run("./ArrayInitializerShorthand.x10","ArrayInitializerShorthand");
    }

    public void test_ArrayOpAssign() {
        run("./ArrayOpAssign.x10","ArrayOpAssign");
    }

    public void test_ArrayOpAssign2() {
        run("./ArrayOpAssign2.x10","ArrayOpAssign2");
    }

    public void test_ArrayOverRegion() {
        run("./ArrayOverRegion.x10","ArrayOverRegion");
    }

    public void test_AsyncFieldAccess() {
        run("./AsyncFieldAccess.x10","AsyncFieldAccess");
    }

    public void test_AsyncTest() {
        run("./AsyncTest.x10","AsyncTest");
    }

    public void test_AsyncTest1() {
        run("./AsyncTest1.x10","AsyncTest1");
    }

    public void test_AtEach() {
        run("./AtEach.x10","AtEach");
    }

    public void test_AtEach2() {
        run("./AtEach2.x10","AtEach2");
    }

    public void test_AtEachLoopOnArray() {
        run("./AtEachLoopOnArray.x10","AtEachLoopOnArray");
    }

    public void test_Atomic1() {
        run("./Atomic1.x10","Atomic1");
    }

    public void test_AtomicMethodTest() {
        run("./AtomicMethodTest.x10","AtomicMethodTest");
    }

    public void test_AtomicReturn() {
        run("./AtomicReturn.x10","AtomicReturn");
    }

    public void test_AtomicTest() {
        run("./AtomicTest.x10","AtomicTest");
    }

    public void test_AwaitTest() {
        run("./AwaitTest.x10","AwaitTest");
    }

    public void test_AwaitTest2() {
        run("./AwaitTest2.x10","AwaitTest2");
    }

    public void test_BasicExternTest1() {
        run("./BasicExternTest1.x10","BasicExternTest1");
    }

    public void test_Boxing0() {
        run("./Boxing0.x10","Boxing0");
    }

    public void test_Boxing1() {
        run("./Boxing1.x10","Boxing1");
    }

    public void test_Boxing2() {
        run("./Boxing2.x10","Boxing2");
    }

    public void test_ClockTest() {
        run("./ClockTest.x10","ClockTest");
    }

    public void test_ClockTest1() {
        run("./ClockTest1.x10","ClockTest1");
    }

    public void test_ClockTest2() {
        run("./ClockTest2.x10","ClockTest2");
    }

    public void test_CommentTest() {
        run("./CommentTest.x10","CommentTest");
    }

    public void test_ConditionalAtomicQueue() {
        run("./ConditionalAtomicQueue.x10","ConditionalAtomicQueue");
    }

    public void test_ConditionalAtomicTest() {
        run("./ConditionalAtomicTest.x10","ConditionalAtomicTest");
    }

    public void test_DistBounds1D() {
        run("./DistBounds1D.x10","DistBounds1D");
    }

    public void test_DistBounds2D() {
        run("./DistBounds2D.x10","DistBounds2D");
    }

    public void test_DistBounds3D() {
        run("./DistBounds3D.x10","DistBounds3D");
    }

    public void test_DistributionTest() {
        run("./DistributionTest.x10","DistributionTest");
    }

    public void test_DistributionTest1() {
        run("./DistributionTest1.x10","DistributionTest1");
    }

    public void test_Exceptions() {
        run("./Exceptions.x10","Exceptions");
    }

    public void test_ExpressionParentheses() {
        run("./ExpressionParentheses.x10","ExpressionParentheses");
    }

    public void test_FinishTest1() {
        run("./FinishTest1.x10","FinishTest1");
    }

    public void test_ForLoop() {
        run("./ForLoop.x10","ForLoop");
    }

    public void test_ForLoop2() {
        run("./ForLoop2.x10","ForLoop2");
    }

    public void test_ForLoop3() {
        run("./ForLoop3.x10","ForLoop3");
    }

    public void test_ForLoop4() {
        run("./ForLoop4.x10","ForLoop4");
    }

    public void test_ForLoopOnArray() {
        run("./ForLoopOnArray.x10","ForLoopOnArray");
    }

    public void test_Foreach2() {
        run("./Foreach2.x10","Foreach2");
    }

    public void test_Future0() {
        run("./Future0.x10","Future0");
    }

    public void test_Future1() {
        run("./Future1.x10","Future1");
    }

    public void test_Future1Boxed() {
        run("./Future1Boxed.x10","Future1Boxed");
    }

    public void test_Future2Boxed() {
        run("./Future2Boxed.x10","Future2Boxed");
    }

    public void test_Future3() {
        run("./Future3.x10","Future3");
    }

    public void test_Future3Boxed() {
        run("./Future3Boxed.x10","Future3Boxed");
    }

    public void test_Future4() {
        run("./Future4.x10","Future4");
    }

    public void test_Future4Boxed() {
        run("./Future4Boxed.x10","Future4Boxed");
    }

    public void test_FutureNullable0() {
        run("./FutureNullable0.x10","FutureNullable0");
    }

    public void test_FutureNullable1Boxed() {
        run("./FutureNullable1Boxed.x10","FutureNullable1Boxed");
    }

    public void test_FutureTest2() {
        run("./FutureTest2.x10","FutureTest2");
    }

    public void test_GameOfLife() {
        run("./GameOfLife.x10","GameOfLife");
    }

    public void test_ImplicitFinal() {
        run("./ImplicitFinal.x10","ImplicitFinal");
    }

    public void test_ImportTest() {
        run("./ImportTest.x10","ImportTest");
    }

    public void test_ImportTestPackage1_SubPackage_T3() {
        run("./ImportTestPackage1/SubPackage/T3.x10","ImportTestPackage1.SubPackage.T3");
    }

    public void test_IntArrayExternUnsafe() {
        run("./IntArrayExternUnsafe.x10","IntArrayExternUnsafe");
    }

    public void test_IntArrayInitializerShorthand() {
        run("./IntArrayInitializerShorthand.x10","IntArrayInitializerShorthand");
    }

    public void test_IntArrayMaxAbs() {
        run("./IntArrayMaxAbs.x10","IntArrayMaxAbs");
    }

    public void test_IntValueArrayInitializerShorthand() {
        run("./IntValueArrayInitializerShorthand.x10","IntValueArrayInitializerShorthand");
    }

    public void test_JGFMolDynBenchSizeA() {
        run("./JGFMolDynBenchSizeA.x10","JGFMolDynBenchSizeA");
    }

    public void test_JGFMonteCarloBenchSizeA() {
        run("./JGFMonteCarloBenchSizeA.x10","JGFMonteCarloBenchSizeA");
    }

    public void test_Jacobi() {
        run("./Jacobi.x10","Jacobi");
    }

    public void test_JacobiExtern() {
        run("./JacobiExtern.x10","JacobiExtern");
    }

    public void test_JacobiSmall() {
        run("./JacobiSmall.x10","JacobiSmall");
    }

    public void test_Jacobi_skewed() {
        run("./Jacobi_skewed.x10","Jacobi_skewed");
    }

    public void test_LiteralTest() {
        run("./LiteralTest.x10","LiteralTest");
    }

    public void test_MiscTest1() {
        run("./MiscTest1.x10","MiscTest1");
    }

    public void test_MpiExample() {
        run("./MpiExample.x10","MpiExample");
    }

    public void test_MpiExample2() {
        run("./MpiExample2.x10","MpiExample2");
    }

    public void test_NopTest() {
        run("./NopTest.x10","NopTest");
    }

    public void test_Nullable0Ref() {
        run("./Nullable0Ref.x10","Nullable0Ref");
    }

    public void test_Nullable1() {
        run("./Nullable1.x10","Nullable1");
    }

    public void test_Nullable2() {
        run("./Nullable2.x10","Nullable2");
    }

    public void test_Nullable5() {
        run("./Nullable5.x10","Nullable5");
    }

    public void test_NullableArray() {
        run("./NullableArray.x10","NullableArray");
    }

    public void test_NullableFuture0() {
        run("./NullableFuture0.x10","NullableFuture0");
    }

    public void test_NullableFuture1() {
        run("./NullableFuture1.x10","NullableFuture1");
    }

    public void test_NullableFuture2() {
        run("./NullableFuture2.x10","NullableFuture2");
    }

    public void test_NullableObject() {
        run("./NullableObject.x10","NullableObject");
    }

    public void test_NullableObject2() {
        run("./NullableObject2.x10","NullableObject2");
    }

    public void test_NullableObject3() {
        run("./NullableObject3.x10","NullableObject3");
    }

    public void test_QueensList() {
        run("./QueensList.x10","QueensList");
    }

    public void test_RandomAccess() {
        run("./RandomAccess.x10","RandomAccess");
    }

    public void test_RandomAccess_int() {
        run("./RandomAccess_int.x10","RandomAccess_int");
    }

    public void test_RandomAccess_long() {
        run("./RandomAccess_long.x10","RandomAccess_long");
    }

    public void test_RandomAccess_longExtern() {
        run("./RandomAccess_longExtern.x10","RandomAccess_longExtern");
    }

    public void test_RandomAccess_skewed() {
        run("./RandomAccess_skewed.x10","RandomAccess_skewed");
    }

    public void test_RegionTest01() {
        run("./RegionTest01.x10","RegionTest01");
    }

    public void test_RegionTest1() {
        run("./RegionTest1.x10","RegionTest1");
    }

    public void test_RegionTest2() {
        run("./RegionTest2.x10","RegionTest2");
    }

    public void test_RegionTestIterator() {
        run("./RegionTestIterator.x10","RegionTestIterator");
    }

    public void test_RemoteAccessCheck() {
        run("./RemoteAccessCheck.x10","RemoteAccessCheck");
    }

    public void test_SimpleDataRace() {
        run("./SimpleDataRace.x10","SimpleDataRace");
    }

    public void test_StringTest() {
        run("./StringTest.x10","StringTest");
    }

    public void test_Unsafe() {
        run("./Unsafe.x10","Unsafe");
    }

    public void test_UserDefinedArray() {
        run("./UserDefinedArray.x10","UserDefinedArray");
    }

    public void test_ValueClass() {
        run("./ValueClass.x10","ValueClass");
    }

    public void test_ValueClassUserDefinedEquals() {
        run("./ValueClassUserDefinedEquals.x10","ValueClassUserDefinedEquals");
    }

    public void test_ValueEquality() {
        run("./ValueEquality.x10","ValueEquality");
    }

    public void test_VariableScope() {
        run("./VariableScope.x10","VariableScope");
    }

    public static void main(String args[]) {
        TestX10_Compiler.Main(TestCompiler.class);
    }
    public static TestSuite suite() {
        return TestX10_Compiler.suite(TestCompiler.class);
    }
}
