
//#line 18 "/Users/nystrom/work/x10/cvs/p3/x10.compiler/src/x10/parser/x10.g"
//
// Licensed Material
// (C) Copyright IBM Corp, 2006
//

//
// This is the grammar specification from the Final Draft of the generic spec.
// It has been modified by Philippe Charles and Vijay Saraswat for use with 
// X10. 
// (1) Removed TypeParameters from class/interface/method declarations
// (2) Removed TypeParameters from types.
// (3) Removed Annotations -- cause conflicts with @ used in places.
// (4) Removed EnumDeclarations.
// 12/28/2004

package x10.parser;

public interface X10Parsersym {
    public final static int
      TK_IntegerLiteral = 54,
      TK_LongLiteral = 55,
      TK_FloatingPointLiteral = 56,
      TK_DoubleLiteral = 57,
      TK_CharacterLiteral = 58,
      TK_StringLiteral = 59,
      TK_MINUS_MINUS = 52,
      TK_OR = 119,
      TK_MINUS = 72,
      TK_MINUS_EQUAL = 105,
      TK_NOT = 70,
      TK_NOT_EQUAL = 120,
      TK_REMAINDER = 106,
      TK_REMAINDER_EQUAL = 107,
      TK_AND = 121,
      TK_AND_AND = 122,
      TK_AND_EQUAL = 108,
      TK_LPAREN = 1,
      TK_RPAREN = 44,
      TK_MULTIPLY = 102,
      TK_MULTIPLY_EQUAL = 109,
      TK_COMMA = 75,
      TK_DOT = 71,
      TK_DIVIDE = 110,
      TK_DIVIDE_EQUAL = 111,
      TK_COLON = 73,
      TK_SEMICOLON = 45,
      TK_QUESTION = 127,
      TK_AT = 4,
      TK_LBRACKET = 7,
      TK_RBRACKET = 80,
      TK_XOR = 123,
      TK_XOR_EQUAL = 112,
      TK_LBRACE = 68,
      TK_OR_OR = 128,
      TK_OR_EQUAL = 113,
      TK_RBRACE = 95,
      TK_TWIDDLE = 76,
      TK_PLUS = 74,
      TK_PLUS_PLUS = 53,
      TK_PLUS_EQUAL = 114,
      TK_LESS = 100,
      TK_LEFT_SHIFT = 101,
      TK_LEFT_SHIFT_EQUAL = 115,
      TK_LESS_EQUAL = 116,
      TK_EQUAL = 94,
      TK_EQUAL_EQUAL = 124,
      TK_GREATER = 79,
      TK_ELLIPSIS = 135,
      TK_ARROW = 46,
      TK_abstract = 67,
      TK_assert = 83,
      TK_boolean = 10,
      TK_break = 84,
      TK_byte = 11,
      TK_case = 103,
      TK_catch = 129,
      TK_char = 12,
      TK_class = 78,
      TK_const = 97,
      TK_continue = 85,
      TK_default = 104,
      TK_do = 86,
      TK_double = 13,
      TK_enum = 138,
      TK_else = 117,
      TK_extends = 130,
      TK_false = 60,
      TK_final = 66,
      TK_finally = 131,
      TK_float = 14,
      TK_for = 87,
      TK_goto = 139,
      TK_if = 88,
      TK_implements = 125,
      TK_import = 132,
      TK_instanceof = 118,
      TK_int = 15,
      TK_interface = 77,
      TK_long = 16,
      TK_native = 133,
      TK_new = 49,
      TK_null = 61,
      TK_package = 136,
      TK_private = 62,
      TK_protected = 63,
      TK_property = 89,
      TK_public = 50,
      TK_return = 90,
      TK_short = 17,
      TK_static = 64,
      TK_strictfp = 69,
      TK_super = 51,
      TK_switch = 91,
      TK_synchronized = 81,
      TK_this = 47,
      TK_throw = 92,
      TK_throws = 134,
      TK_transient = 98,
      TK_true = 65,
      TK_try = 93,
      TK_void = 48,
      TK_volatile = 99,
      TK_while = 82,
      TK_activitylocal = 36,
      TK_any = 137,
      TK_async = 18,
      TK_ateach = 19,
      TK_atomic = 8,
      TK_await = 20,
      TK_boxed = 37,
      TK_clocked = 9,
      TK_compilertest = 38,
      TK_current = 39,
      TK_extern = 21,
      TK_finish = 22,
      TK_foreach = 23,
      TK_fun = 40,
      TK_future = 24,
      TK_here = 25,
      TK_local = 26,
      TK_method = 41,
      TK_mutable = 27,
      TK_next = 28,
      TK_nonblocking = 29,
      TK_now = 30,
      TK_nullable = 31,
      TK_or = 6,
      TK_placelocal = 42,
      TK_reference = 43,
      TK_safe = 3,
      TK_self = 32,
      TK_sequential = 33,
      TK_unsafe = 5,
      TK_value = 2,
      TK_when = 34,
      TK_EOF_TOKEN = 126,
      TK_IDENTIFIER = 35,
      TK_SlComment = 140,
      TK_MlComment = 141,
      TK_DocComment = 142,
      TK_GREATER_EQUAL = 143,
      TK_RIGHT_SHIFT = 144,
      TK_UNSIGNED_RIGHT_SHIFT = 145,
      TK_RIGHT_SHIFT_EQUAL = 146,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 147,
      TK_ErrorId = 96,
      TK_ERROR_TOKEN = 148;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "value",
                 "safe",
                 "AT",
                 "unsafe",
                 "or",
                 "LBRACKET",
                 "atomic",
                 "clocked",
                 "boolean",
                 "byte",
                 "char",
                 "double",
                 "float",
                 "int",
                 "long",
                 "short",
                 "async",
                 "ateach",
                 "await",
                 "extern",
                 "finish",
                 "foreach",
                 "future",
                 "here",
                 "local",
                 "mutable",
                 "next",
                 "nonblocking",
                 "now",
                 "nullable",
                 "self",
                 "sequential",
                 "when",
                 "IDENTIFIER",
                 "activitylocal",
                 "boxed",
                 "compilertest",
                 "current",
                 "fun",
                 "method",
                 "placelocal",
                 "reference",
                 "RPAREN",
                 "SEMICOLON",
                 "ARROW",
                 "this",
                 "void",
                 "new",
                 "public",
                 "super",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "false",
                 "null",
                 "private",
                 "protected",
                 "static",
                 "true",
                 "final",
                 "abstract",
                 "LBRACE",
                 "strictfp",
                 "NOT",
                 "DOT",
                 "MINUS",
                 "COLON",
                 "PLUS",
                 "COMMA",
                 "TWIDDLE",
                 "interface",
                 "class",
                 "GREATER",
                 "RBRACKET",
                 "synchronized",
                 "while",
                 "assert",
                 "break",
                 "continue",
                 "do",
                 "for",
                 "if",
                 "property",
                 "return",
                 "switch",
                 "throw",
                 "try",
                 "EQUAL",
                 "RBRACE",
                 "ErrorId",
                 "const",
                 "transient",
                 "volatile",
                 "LESS",
                 "LEFT_SHIFT",
                 "MULTIPLY",
                 "case",
                 "default",
                 "MINUS_EQUAL",
                 "REMAINDER",
                 "REMAINDER_EQUAL",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "LESS_EQUAL",
                 "else",
                 "instanceof",
                 "OR",
                 "NOT_EQUAL",
                 "AND",
                 "AND_AND",
                 "XOR",
                 "EQUAL_EQUAL",
                 "implements",
                 "EOF_TOKEN",
                 "QUESTION",
                 "OR_OR",
                 "catch",
                 "extends",
                 "finally",
                 "import",
                 "native",
                 "throws",
                 "ELLIPSIS",
                 "package",
                 "any",
                 "enum",
                 "goto",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "GREATER_EQUAL",
                 "RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
