#! /bin/ksh

export RT_GRQ=ON
prog=multi
prog="Transpose2a -y 20 -x 32 -P 4 -Q 4 -N 99"
prog="Transpose2b -y 20 -x 20 -P 4 -Q 4 -N 5"
prog="Transpose2b -y 20 -x 32 -P 8 -Q 8 -N 5"
prog="Transpose2b -y 20 -x 20 -P 4 -Q 4 -N 25"
prog="TransposePlus -y 400 -x 400 -P 4 -Q 4 -N 5"
prog="Transpose2c -debug -y 4 -x 4 -P 2 -Q 3 -N 5"
prog="Transpose2b -y 400 -x 400 -P 2 -Q 3 -N 5"
prog="Transpose2d -y 400 -x 400 -P 2 -Q 3 -N 8"
prog="Transpose2e -y 800 -x 800 -P 3 -Q 4 -N 10"

if [[ $# -eq 0 || $1 -eq 0 ]] then
  export TRACEIT=boo
fi
#if [[ ! -e vv.cfg ]]; then
# genConfig -place 4 -vm 6 -host milan -o vv.cfg
#fi
export VMID=${1:-0}

set -x
./x10 -mx 1000M -Dx10.configuration=12way.cfg -vm ${1:-0} $prog
